<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Team name: ACDC  Team members:  Khuyen Nguyen kngu0086@student.monash.edu  Khanh Pham mpha0054@student.monash.edu  Evan Ginting egin0003@student.monash.edu  Amrita Jena ajen0022@student.monash.edu  Phuong Mai pmai0003@student.monash.edu">

<title>Weeping Mulla Mulla: Ptilotus Calostachyus</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="report_files/libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="report_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="report_files/libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="report_files/libs/leaflet-1.3.1/leaflet.js"></script>
<link href="report_files/libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="report_files/libs/proj4-2.6.2/proj4.min.js"></script>
<script src="report_files/libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="report_files/libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="report_files/libs/leaflet-binding-2.2.0/leaflet.js"></script>
<script src="report_files/libs/leaflet-providers-1.13.0/leaflet-providers_1.13.0.js"></script>
<script src="report_files/libs/leaflet-providers-plugin-2.2.0/leaflet-providers-plugin.js"></script>
<script src="report_files/libs/plotly-binding-4.10.2/plotly.js"></script>
<script src="report_files/libs/typedarray-0.1/typedarray.min.js"></script>
<link href="report_files/libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="report_files/libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="report_files/libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="report_files/libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="report_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="report_files/libs/datatables-binding-0.28/datatables.js"></script>
<link href="report_files/libs/dt-core-1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="report_files/libs/dt-core-1.13.4/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="report_files/libs/dt-core-1.13.4/js/jquery.dataTables.min.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data description</a>
  <ul class="collapse">
  <li><a href="#occurences-data" id="toc-occurences-data" class="nav-link" data-scroll-target="#occurences-data">Occurences data</a></li>
  <li><a href="#weather-data" id="toc-weather-data" class="nav-link" data-scroll-target="#weather-data">Weather data</a></li>
  <li><a href="#tourism-data" id="toc-tourism-data" class="nav-link" data-scroll-target="#tourism-data">Tourism Data</a></li>
  </ul></li>
  <li><a href="#initial-data-analysis" id="toc-initial-data-analysis" class="nav-link" data-scroll-target="#initial-data-analysis">Initial data analysis</a>
  <ul class="collapse">
  <li><a href="#occurences-data-1" id="toc-occurences-data-1" class="nav-link" data-scroll-target="#occurences-data-1">Occurences Data</a></li>
  <li><a href="#weather-data-1" id="toc-weather-data-1" class="nav-link" data-scroll-target="#weather-data-1">Weather Data</a></li>
  <li><a href="#tourism-data-1" id="toc-tourism-data-1" class="nav-link" data-scroll-target="#tourism-data-1">Tourism Data</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory data analysis</a>
  <ul class="collapse">
  <li><a href="#the-analysis-of-our-expectations" id="toc-the-analysis-of-our-expectations" class="nav-link" data-scroll-target="#the-analysis-of-our-expectations">The Analysis of Our Expectations</a></li>
  <li><a href="#the-weather-analysis" id="toc-the-weather-analysis" class="nav-link" data-scroll-target="#the-weather-analysis">The Weather Analysis</a></li>
  <li><a href="#tourism-analysis" id="toc-tourism-analysis" class="nav-link" data-scroll-target="#tourism-analysis">Tourism Analysis</a></li>
  <li><a href="#weeping-mulla-mulla-eco-tourism" id="toc-weeping-mulla-mulla-eco-tourism" class="nav-link" data-scroll-target="#weeping-mulla-mulla-eco-tourism">Weeping Mulla Mulla Eco-Tourism</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a>
  <ul class="collapse">
  <li><a href="#websites" id="toc-websites" class="nav-link" data-scroll-target="#websites">Websites</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Weeping Mulla Mulla: Ptilotus Calostachyus</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><strong>Team name:</strong> ACDC <br> <strong>Team members:</strong> <br> Khuyen Nguyen <em>kngu0086@student.monash.edu</em> <br> Khanh Pham <em>mpha0054@student.monash.edu</em> <br> Evan Ginting <em>egin0003@student.monash.edu</em> <br> Amrita Jena <em>ajen0022@student.monash.edu</em> <br> Phuong Mai <em>pmai0003@student.monash.edu</em> </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The <em>Ptilotus calostachyus&nbsp;F.Muell</em>, which is also known as the Weeping Mulla Mulla, is an endemic plant that is commonly found in the Western Australia territory (Florabase n.&nbsp;d.). This species thrives in arid region, particular in sandy habitats with red and stony plains (Florabase n.&nbsp;d.). Being a <em>perennial</em> plant, it can live up to more than two years with the seasonal pattern of being dormant in the winter and sprouting again in springtime (Florabase n.&nbsp;d.). Moreover, <strong>Weeping Mulla Mulla</strong> displays erect or spreading, herb or shrub characteristics, meaning that it can be found as a tall plant and/or covering an area, as well as with/without a woody body. They can grow from 0.2 to 2 meters tall with pink-white flowers, blooming from March to October. Despite the widespread of its coverage, there are little to none organized sighting campaign of the Weeping Mulla Mulla due to the outback nature of its habitat and lesser popularity as compared to other iconic Australia ecotourism species.</p>
<p>Five expectations when exploring the Weeping Mulla Mulla sightings:</p>
<ul>
<li><p>We expect most of the sightings to occur between March to October.</p></li>
<li><p>We expect most of the sighting location to be in the Western Australia territory.</p></li>
<li><p>We expect the sightings to be consistent numbers of sightings with an increasing trend as sighting/reporting/monitoring methods become better. However, this anticipation will exclude years during the COVID-19 pandemic. Since the data relies on human observation, there may be fewer sightings due to a lack of reporting.</p></li>
<li><p>We expect the sightings to be clustered in areas with a water source as the plant prefers harsh, dry, and hot sandy habitats.</p></li>
<li><p>We expect the sightings records to increase after rainfall events, as plants typically begin to bloom after wet season, which is around June - August for Perth.</p></li>
</ul>
<p>This report aims to provide a comprehensive analysis of the <strong>Weeping Mulla Mulla</strong>, utilising primary data sources from the <em>ALA Atlas of Living Australia</em> and the <em>Global Historical Climatology Network (GHCN)</em> database.</p>
<p>Throughout this exploration of expectations, numerous intriguing observations were uncovered that were not initially anticipated. Notably, the employment of <code>spData</code> and <code>leaflet</code> effectively visualised these findings and allows for interactivity.</p>
<p>It is important to note several limitations that have affected the final analysis. Firstly, there is a scarcity of observations, primarily because this plant is not commonly sought after or reported by individuals. Secondly, the absence of weather recordings in remote areas may lead to gaps in the dataset.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://static.inaturalist.org/photos/54862576/medium.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data description</h2>
<section id="occurences-data" class="level3">
<h3 class="anchored" data-anchor-id="occurences-data">Occurences data</h3>
<p>Below is the code to download the raw data directly from <em>ALA Atlas of Living Australia</em>.</p>
<p>The basis of record was filtered to <code>HUMAN_OBSERVATION</code> only. The intention of this analysis is to focus solely on sightings of the species in the wild, and differentiate between specimens that are preserved, collected samples, or in controlled environments such as museums.</p>
<p>We have also checked the <code>BASIS_OF_RECORD_INVALID</code> to determine the reliability of each observation, in which all the <code>TRUE</code> results were removed in the process of sub-setting <code>HUMAN_OBSERVATION</code> entry in the <code>basisOfRecord</code>.</p>
<p>The other options, such as <code>LIVING SPECIMEN</code>, could imply captivity or control, <code>PRESERVED SPECIMEN</code> typically refers to non-living specimens, and <code>OCCURRENCE</code> was too general to confirm its wild state.</p>
<p>The data obtained from the Atlas of Living Australia website combines information from multiple sources and includes various variables such as location, date, time, scientific names, resource names, species status, and more. The raw data set contains 359 observations and 15 variables.</p>
<p>For the analysis, the data is filtered to primarily focus on utilising the location and event time data. This is because the other variables do not contribute significantly to meaningful insights. However, a comprehensive dictionary of all the variables is provided below:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption><strong>Data Dictionary for the Weeping Mulla Mulla dataset</strong></caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">decimalLatitude</td>
<td style="text-align: left;">Latitude value of sighting in decimal format.</td>
</tr>
<tr class="even">
<td style="text-align: left;">decimalLongitude</td>
<td style="text-align: left;">Longitude value of sighting in decimal format.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">eventDate</td>
<td style="text-align: left;">Recorded sighting date and time in the format YYYY-MM-DD, hh:mm:ss. In some cases, no time was recorded, and therefore, it is left as 00:00:00.</td>
</tr>
<tr class="even">
<td style="text-align: left;">scientificName</td>
<td style="text-align: left;">The scientific name of the observed species.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">taxonConceptID</td>
<td style="text-align: left;">The taxonomy website ID: <a href="https://id.biodiversity.org.au/node/apni/2910906">Ptilotus calostachyus</a>.</td>
</tr>
<tr class="even">
<td style="text-align: left;">recordID</td>
<td style="text-align: left;">The record ID of each observation.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dataResourceName</td>
<td style="text-align: left;">The data resource associated with the observation: <a href="https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2910906#data-partners">List of 23 partners</a>.</td>
</tr>
<tr class="even">
<td style="text-align: left;">occurrenceStatus</td>
<td style="text-align: left;">The occurrence status: Present.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">eventRemarks</td>
<td style="text-align: left;">Any additional remarks or comments related to the observation.</td>
</tr>
<tr class="even">
<td style="text-align: left;">eventTime</td>
<td style="text-align: left;">Time of the event recorded in the format hh:mm:ss, including the time zone difference.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">eventID</td>
<td style="text-align: left;">The event ID of each obsercation.</td>
</tr>
<tr class="even">
<td style="text-align: left;">samplingEffort</td>
<td style="text-align: left;">A description of the effort or area that was surveyed or sampled to locate the species.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">samplingProtocol</td>
<td style="text-align: left;">The protocol that was used to sample the species.</td>
</tr>
<tr class="even">
<td style="text-align: left;">basisOfRecord</td>
<td style="text-align: left;">Indicates how the record was made: Human observation.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cl959</td>
<td style="text-align: left;">Denotes the local government area where the observation was made.</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="weather-data" class="level3">
<h3 class="anchored" data-anchor-id="weather-data">Weather data</h3>
<p>The distribution of the Weeping Mulla Mulla commonly spans the local government areas (LGAs) of Ashburton, Broome, Derby-West Kimberley, East Pilbara, Halls Creek, Karratha, Laverton, Meekatharra, Ngaanyatjarraku, Port Hedland, Upper Gascoyne, and Wyndham-East Kimberley, as per findings from (<a href="https://florabase.dbca.wa.gov.au/browse/profile.php/2704">Florabase</a>).</p>
<p>Since weather is an important factor in the occurrences of species, the Global Historical Climatology Network (GHCN) database contains weather station data that are useful for analysing trends in weather patterns and precipitation. Obtaining the data via the <code>rnoaa</code> package for Australia was completed using the code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>aus_stations <span class="ot">&lt;-</span> <span class="fu">ghcnd_stations</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_starts</span>(id, <span class="st">"ASN"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(last_year <span class="sc">&gt;=</span> <span class="dv">2020</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">wmo_id =</span> <span class="fu">as.numeric</span>(wmo_id),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">name =</span> <span class="fu">str_to_lower</span>(name)) <span class="sc">|&gt;</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>state, <span class="sc">-</span>gsn_flag) <span class="sc">|&gt;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(element <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"PRCP"</span>, <span class="st">"TMAX"</span>, <span class="st">"TMIN"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>(element<span class="sc">:</span> last_year) <span class="sc">|&gt;</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">nrow</span>(data) <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>data) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="table">
<caption><strong>Data Dictionary for the All AU Weather Station</strong></caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variables</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>id</td>
<td>An identifier associated with a specific station.</td>
</tr>
<tr class="even">
<td>latitude</td>
<td>The latitude (in decimal degrees) of the station’s location.</td>
</tr>
<tr class="odd">
<td>longitude</td>
<td>The longitude (in decimal degrees) of the station’s location.</td>
</tr>
<tr class="even">
<td>elevation</td>
<td>The elevation (in meters) of the station’s location.</td>
</tr>
<tr class="odd">
<td>name</td>
<td>The name or description of the station.</td>
</tr>
<tr class="even">
<td>wmo_id</td>
<td>The World Meteorological Organization (WMO) identifier associated with the station.</td>
</tr>
</tbody>
</table>
<section id="obtaining-weather-data-for-tennant-creek" class="level4">
<h4 class="anchored" data-anchor-id="obtaining-weather-data-for-tennant-creek">Obtaining weather data for Tennant Creek</h4>
<p>The code for obtaining precipitation, maximum temperature, and minimum temperature data for Tennant Creek is provided below by filtering using the station ID ASN00015135:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tennant_creek_airport <span class="ot">&lt;-</span> aus_stations <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(id <span class="sc">==</span> <span class="st">"ASN00015135"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ts =</span> <span class="fu">list</span>(<span class="fu">meteo_pull_monitors</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">monitors =</span> id, <span class="at">var =</span> <span class="fu">c</span>(<span class="st">"PRCP"</span>, <span class="st">"TMAX"</span>, <span class="st">"TMIN"</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_min =</span> <span class="st">"2004-01-01"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">date_max =</span> <span class="st">"2023-09-13"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(<span class="sc">-</span>id))) <span class="sc">|&gt;</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">lat =</span> latitude, <span class="at">long =</span> longitude, <span class="at">elev =</span> elevation) <span class="sc">|&gt;</span> </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, long, lat, elev, name, wmo_id, ts) <span class="sc">%&gt;%</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(ts) <span class="sc">|&gt;</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tmax =</span> tmax<span class="sc">/</span><span class="dv">10</span>, <span class="at">tmin =</span> tmin<span class="sc">/</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="table">
<caption><strong>Data Dictionary for the Tennant Creek Weather Station</strong></caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variables</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>id</td>
<td>An identifier associated with a specific location or station.</td>
</tr>
<tr class="even">
<td>long</td>
<td>The longitude (in decimal degrees) of the location.</td>
</tr>
<tr class="odd">
<td>lat</td>
<td>The latitude (in decimal degrees) of the location.</td>
</tr>
<tr class="even">
<td>elev</td>
<td>The elevation (in meters) of the location.</td>
</tr>
<tr class="odd">
<td>name</td>
<td>The name or description of the location or station.</td>
</tr>
<tr class="even">
<td>wmo_id</td>
<td>The World Meteorological Organization (WMO) identifier associated with the location.</td>
</tr>
<tr class="odd">
<td>date</td>
<td>The date of the recorded weather data.</td>
</tr>
<tr class="even">
<td>prcp</td>
<td>Precipitation amount.</td>
</tr>
<tr class="odd">
<td>tmax</td>
<td>Maximum temperature.</td>
</tr>
<tr class="even">
<td>tmin</td>
<td>Minimum temperature.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="tourism-data" class="level3">
<h3 class="anchored" data-anchor-id="tourism-data">Tourism Data</h3>
<p>We are going to extend our focus beyond the mere observation of this wild flower by looking into the tourism activities within its habitat. Leveraging data sourced from Tourism Research Australia (TRA), our objective is to discern whether the tourist activities have played a role in the number of Weeping Mulla Mulla sightings. In doing so, there are some steps that have to be done to combine the occurence information and the tourism activities.</p>
<p>As we have been given the tourism dataset, below is the code and the table containing all variables in this data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/tourism.rda"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="table">
<caption><strong>Data Dictionary for the Tourism Data</strong></caption>
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variables</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quarter</td>
<td>The Year and Quarter when the trips happened</td>
</tr>
<tr class="even">
<td>Region</td>
<td>The Region where the people going to. Region is equivalent to Statistical Area 2.</td>
</tr>
<tr class="odd">
<td>Purpose</td>
<td>The reason of the trips (Business, Holiday, Other).</td>
</tr>
<tr class="even">
<td>Trips</td>
<td>Number of people doing the trip.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="initial-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="initial-data-analysis">Initial data analysis</h2>
<section id="occurences-data-1" class="level3">
<h3 class="anchored" data-anchor-id="occurences-data-1">Occurences Data</h3>
<section id="data-cleaning" class="level4">
<h4 class="anchored" data-anchor-id="data-cleaning">Data cleaning</h4>
<p>For Occurence Data, only location and event time variables significantly contribute to the analysis. Methods for selecting and renaming variables, extracting time variables from the date, and removing unnecessary strings and missing values were applied before saving a clean version for further analysis. The code for data cleaning can be referred to below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>weeping_mulla_mulla <span class="ot">&lt;-</span> storage <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(decimalLongitude, decimalLatitude, eventDate, cl959) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">longitude =</span> decimalLongitude,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">latitude =</span> decimalLatitude,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">lga =</span> cl959) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">eventDate =</span> <span class="fu">as.Date</span>(eventDate),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">Year =</span> lubridate<span class="sc">::</span><span class="fu">year</span>(eventDate),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Month =</span> lubridate<span class="sc">::</span><span class="fu">month</span>(eventDate),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">monthName =</span> lubridate<span class="sc">::</span><span class="fu">month</span>(eventDate, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Day =</span> lubridate<span class="sc">::</span><span class="fu">day</span>(eventDate),</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">lga =</span> <span class="fu">str_remove</span>(lga, <span class="st">"</span><span class="sc">\\</span><span class="st">(.*"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(eventDate)) <span class="sc">%&gt;%</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(longitude)) </span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(weeping_mulla_mulla, <span class="at">file =</span> (<span class="st">"data/weeping_mulla_mulla.rda"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="checking-data-quality-weeping-mulla-mulla" class="level4">
<h4 class="anchored" data-anchor-id="checking-data-quality-weeping-mulla-mulla">Checking data quality (Weeping Mulla Mulla)</h4>
<p>We will be using <code>visdat</code> library to check for data type errors</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1: vis_dat() results of weeping_mulla_mulla</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Discussion</strong></p>
<p>In <a href="#fig-plots1">Figure&nbsp;1</a>, the result of <code>visdat</code> does not signify any anomalies that needed to be addressed before proceeding with further analysis.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2: vis_guess() results of weeping_mulla_mulla</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Discussion</strong></p>
<p>In <a href="#fig-plots2">Figure&nbsp;2</a>, <code>vis_guess</code> shows that the <em>longitude</em> and <em>latitude</em> columns both have a record with potentially integer coordinates entry. While this is a sign of rounding given that the coordinates span from a length of values with 5 decimal places precision, we believe this value does not need any alterations as sighting coordinates span across a very wide geographical area, making rounding to the nearest whole number (1.0 degree is 111 kilometers) insignificant in our spatial analysis.</p>
</section>
</section>
<section id="weather-data-1" class="level3">
<h3 class="anchored" data-anchor-id="weather-data-1">Weather Data</h3>
<p>From the initial weather data that we extracted using rnoaa package, We obtained data for all weather stations across Australia. This is too broad for our analysis, also the sightings of Weeping Mulla Mulla are not even recorded in all parts of Australia. Therefore, some data transformation are needed. We will filter out the location where Weeping Mulla Mulla are recorded to make the analysis more precise.</p>
<p>When filtering the weather stations to be within the vicinity of Weeping Mulla Mulla, it becomes evident that the <strong>Weeping Mulla Mulla</strong> is found in the vicinity of 42 weather stations.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The triangles on the map represent the locations of 42 weather stations. The purple points, with varying alpha and size settings, help to identify the areas with the highest occurrence rates. Notably, the red triangle represents the Tennant Creek Airport weather station, which records the majority of observations. Given this focus, the analysis can be narrowed down by filtering the weather station data specifically for Tennant Creek.</p>
<p>For another view of these findings, the same map was recreated using <code>leaflet</code>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="leaflet html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-07bc5a4a0d76c6c52844" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-07bc5a4a0d76c6c52844">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["Esri.DeLorme",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircleMarkers","args":[[-24.92637,-24.88139,-24.831,-24.831,-23.635464,-23.347663,-23.343507,-23.249701,-22.98952,-22.968522,-22.915269,-22.884576,-22.721379,-22.703481,-22.603638,-22.602916,-22.596658,-22.563828,-22.52959,-22.489682,-22.489275,-22.488925,-22.476578,-22.4755,-22.473027,-22.471344,-22.469722,-22.463235,-22.452836,-22.388645,-22.388624,-22.257155,-22.16544,-21.97379,-21.945856,-21.870746,-21.838707,-21.733533,-21.72664,-21.617833,-21.617833,-21.614884,-21.582853,-21.579594,-21.576002,-21.574056,-21.57277,-21.541103,-21.511828,-21.481834,-21.418448,-21.331,-21.312727,-21.278442,-21.205871,-21.204668,-21.177544,-21.173701,-21.16261,-21.15763,-21.126622,-21.10231,-21.101738,-21.050878,-21.048372,-21.048274,-21.043195,-21.032429,-21.019396,-21.015883,-21.009417,-21.009199,-21.003011,-21.001455,-20.997189,-20.99717,-20.994475,-20.994224,-20.991712,-20.988414,-20.988057,-20.985577,-20.982557,-20.982205,-20.97943,-20.976355,-20.97481,-20.972174,-20.969205,-20.965197,-20.963884,-20.960817,-20.960405,-20.960334,-20.958574,-20.95829,-20.956299,-20.955891,-20.9554,-20.954385,-20.954385,-20.951821,-20.950134,-20.949971,-20.94859,-20.945884,-20.945597,-20.944745,-20.939384,-20.93931,-20.93329,-20.930955,-20.926775,-20.92642,-20.921444,-20.916348,-20.914099,-20.910702,-20.908404,-20.907149,-20.905168,-20.903123,-20.900206,-20.892721,-20.889404,-20.888558,-20.888291,-20.881672,-20.866842,-20.866054,-20.862992,-20.848869,-20.844714,-20.838397,-20.838172,-20.836,-20.83482,-20.833808,-20.828179,-20.822859,-20.819184,-20.817223,-20.808104,-20.799552,-20.793407,-20.793407,-20.788768,-20.770423,-20.58866,-20.585863,-20.449183,-20.409496,-20.226387,-20.0766,-20.017908,-20.00436,-20,-19.991705,-19.952702,-19.900764,-19.842912,-19.82652,-19.795638,-19.794451,-19.791679,-19.791318,-19.786672,-19.782027,-19.777635,-19.776906,-19.776696,-19.776375,-19.77336,-19.77206,-19.768752,-19.764023,-19.761428,-19.761268,-19.760729,-19.760633,-19.760527,-19.759499,-19.759389,-19.759276,-19.759269,-19.759222,-19.75542,-19.754155,-19.753509,-19.751575,-19.746024,-19.744552,-19.744412,-19.739859,-19.736255,-19.735764,-19.732994,-19.731928,-19.729218,-19.724622,-19.721289,-19.721283,-19.721239,-19.721047,-19.721043,-19.721024,-19.720985,-19.720983,-19.717655,-19.716908,-19.70119,-19.692061,-19.67612,-19.650208,-19.63742,-19.616018,-19.610897,-19.609871,-19.60759,-19.60758,-19.60755,-19.607541,-19.607528,-19.607499,-19.607491,-19.607481,-19.607456,-19.607383,-19.579463,-19.574444,-19.435337,-19.427922,-19.32684,-19.3202,-19.31884,-19.27083,-19.2545,-19.2541,-19.195281,-19.173118,-19.042738,-19.042377,-19.039827,-18.90047,-18.8978,-18.828771,-18.79834,-18.754633,-18.749842,-18.748925,-18.748544,-18.748544,-18.748322,-18.747823,-18.747411,-18.73309,-18.72936,-18.63607,-18.625522,-18.604107,-18.601575,-18.533247,-18.522517,-18.518889,-18.518611,-18.51124,-18.504358,-18.488,-18.465887,-18.443251,-18.42128,-18.395194,-18.360472,-18.354122,-18.335,-18.332312,-18.224822,-18.220556,-18.08586,-17.982737,-17.97502,-17.971977,-17.935497,-17.7089,-17.691004,-17.67596,-17.64086,-17.63523,-17.524972,-17.39883,-17.39372,-17.374737,-17.35674,-17.35503,-17.32864,-17.32629,-17.120244,-16.970676,-16.94958,-16.92838,-16.855777,-16.37848,-16.029135,-16.028118,-15.965,-15.860867,-15.848218,-15.67655,-15.66423,-15.639855,-15.606519,-15.555047,-15.452222,-15.14837],[131.167,129.20921,128.911,128.911,132.739944,119.727495,119.744828,119.57028,118.922125,119.393121,118.254643,119.173191,118.329345,117.761979,118.112712,118.118161,118.100861,118.485642,118.457322,118.483837,118.73587,118.735313,118.552441,118.5516,118.550035,118.557264,118.555556,118.183853,118.365023,118.262928,118.262913,117.985955,121.674438,115.644651,118.686019,115.610191,115.639928,120.442313,118.525279,121.576438,121.576438,134.110543,117.093247,117.067147,118.82902,133.843326,117.21627,117.056997,134.156373,133.83388,117.153164,117.244,130.867158,118.402345,119.72295,119.727428,134.307554,134.268232,134.296845,134.309756,134.241943,119.766164,119.16566,118.617867,134.440771,134.41952,134.483465,134.428233,118.903261,134.326383,134.325027,134.343223,134.327259,134.338282,134.290878,134.27761,134.35363,134.27977,134.174107,134.310142,134.287092,134.299004,134.279172,134.26634,134.274617,134.313131,134.280335,134.263965,134.296888,134.226754,134.363823,134.243302,134.330672,134.356816,134.195354,134.275094,134.365,134.357336,134.277638,134.174091,134.174091,134.221888,134.354494,134.258937,134.246874,134.241146,134.254467,134.365491,134.199256,134.208604,134.244065,134.230853,134.202083,134.190112,134.262982,134.366521,134.213804,134.206187,134.225074,134.215456,134.24911,134.214188,134.242606,134.327235,134.21349,134.246326,134.41745,134.227788,134.322598,134.226521,134.223775,134.26409,134.232025,117.833305,117.833886,119.561,134.268048,134.223059,134.23881,134.246982,134.243129,134.215022,134.231892,134.208985,134.109889,134.109889,134.126687,116.891045,134.278736,134.263961,119.997503,134.244157,119.58767,136.9164,119.960789,137.192975,136,136.644527,136.493115,129.358895,136.156425,130.42548,133.90063,133.840098,133.900447,133.900478,133.900329,133.900189,133.900057,133.855907,133.841543,133.84627,133.899914,133.93166,133.899803,133.894958,133.885823,133.876214,133.866664,133.871561,133.861884,133.902758,133.917361,133.907579,133.912371,133.922526,133.89769,133.843252,133.925227,133.895378,133.941376,133.889271,133.916517,133.914009,133.844622,133.911852,133.881774,133.909664,133.878947,133.90584,133.960553,133.894159,133.951189,133.89888,133.88951,133.979339,133.884757,133.9037,121.566642,133.91218,129.79075,133.881448,129.77735,133.851343,129.61747,133.861222,134.20883,134.209926,133.814212,133.789584,133.819171,133.804058,133.808911,133.765796,133.853439,133.84338,133.854699,133.760743,134.199027,130.765556,135.429745,135.393507,135.22021,134.851295,135.21801,130.63646,130.61571,130.6301,126.861435,127.789748,121.66641,121.667664,121.667642,131.60233,129.6975,126.522488,126.533373,136.805083,126.107994,126.110043,126.108503,126.108878,126.108758,126.108592,136.871472,130.32092,126.85851,129.6217,136.642528,121.96645,137.113133,136.595361,122.021237,136.954444,136.954247,127.567228,136.623056,136.812025,133.861088,133.608311,122.112595,135.8687,135.751756,135.892792,130.613056,133.804075,134.345065,127.673889,132.68062,125.227565,133.6805,134.805647,130.824873,131.5031,134.761084,133.62404,133.60361,133.58891,135.696785,133.43896,130.38531,133.439422,130.57042,130.40294,130.22855,133.43811,134.047839,130.308192,130.13693,130.14078,133.455311,134.7343,130.777197,130.783748,127.932,127.947344,131.168776,131.31776,131.32181,130.867289,131.109015,131.288522,129.321111,132.87892],10,null,null,{"interactive":true,"className":"","stroke":false,"color":"#c599b2","weight":5,"opacity":0.5,"fill":true,"fillColor":"#c599b2","fillOpacity":0.1},null,null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addCircleMarkers","args":[[-15.51,-16.4181,-15.3797,-18.2292,-17.0156,-15.7814,-16.6381,-17.9475,-18.6844,-17.3706,-16.4514,-17.5736,-18.1814,-19.7419,-20.1078,-20.3725,-20.7097,-20.7594,-21.1756,-21.1906,-23.4169,-23.1725,-21.7125,-16.2636,-15.7426,-16.4423,-16.0757,-16.403,-18.3325,-17.3871,-15.7442,-18.637,-17.5521,-19.6423,-20.1883,-23.7951,-23.4564,-22.9494,-22.4518,-24.2914,-23.27,-20.1824],[128.1503,126.1025,126.3114,127.6636,128.2175,128.71,128.4517,122.2353,121.7803,123.6611,123.0086,123.8217,125.5619,120.8436,119.5811,118.6317,116.7742,117.1583,119.7497,115.9797,119.7989,117.7494,122.2281,133.3782,136.8192,136.076,136.3041,131.0145,130.6358,131.1166,131.9182,135.945,133.5407,134.1833,130.0161,133.889,134.6849,136.1442,133.6377,131.5488,129.38,130.0148],3,null,null,{"interactive":true,"className":"","stroke":false,"color":"#222233","weight":5,"opacity":0.5,"fill":true,"fillColor":"#222233","fillOpacity":1},null,null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addCircleMarkers","args":[-19.6423,134.1833,5,null,null,{"interactive":true,"className":"","stroke":false,"color":"red","weight":5,"opacity":0.5,"fill":true,"fillColor":"red","fillOpacity":1},null,null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"setView":[[-21.833,128.583],5,[]],"limits":{"lat":[-24.92637,-15.14837],"lng":[115.610191,137.192975]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<section id="transforming-weather-station-data" class="level4">
<h4 class="anchored" data-anchor-id="transforming-weather-station-data">Transforming Weather Station Data</h4>
<p>The code below will add some new variables to the data that will be utilised in the analysis in later part. The new variables was created to extract Year, Quarter, and Month from the date of weather report, also we added a new variable to get the daily average temperature.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>tca <span class="ot">&lt;-</span> tennant_creek_airport <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="at">Year =</span> lubridate<span class="sc">::</span><span class="fu">year</span>(date),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">Quarter =</span> lubridate<span class="sc">::</span><span class="fu">quarter</span>(date),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">Month =</span> lubridate<span class="sc">::</span><span class="fu">month</span>(date),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">avg_tmp =</span> (tmax <span class="sc">+</span> tmin) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>tca_cb <span class="ot">&lt;-</span> <span class="fu">as_cubble</span>(<span class="fu">as_tibble</span>(tca),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">key =</span> id,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">index =</span> date,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">coords =</span> <span class="fu">c</span>(long, lat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Tennant Creek in Barkly Region</strong></p>
<p>The <code>weeping_mulla_mulla</code> dataset has included local government information. Given that Tennant Creek is situated in the local government area of Barkly, the final step involves integrating the species data set with temperature data from weather stations and highlighting those observations belonging to the Barkly region.</p>
<p>A new column named <code>sighting</code> is created. This column serves the crucial purpose of indicating whether a sighting occurred on a particular day or not and whether temperature data is available. Consequently, as all the observations within the Barkly region have corresponding temperature data, a comprehensive dataset can be generated that encompasses both observational data and daily weather information. Dates with records in this region would be given <strong>1</strong> while others would be <strong>0</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>temperature <span class="ot">&lt;-</span> tennant_creek_airport <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(weeping_mulla_mulla, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"date"</span> <span class="ot">=</span> <span class="st">"eventDate"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sighting =</span> <span class="fu">ifelse</span>(lga <span class="sc">==</span> <span class="st">"Barkly "</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sighting =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(sighting), <span class="dv">0</span>, sighting)) <span class="sc">%&gt;%</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="dv">11</span><span class="sc">:-</span><span class="dv">17</span>) </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(temperature, <span class="at">file =</span> (<span class="st">"data/temperature.rda"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="checking-data-quality-temperature" class="level4">
<h4 class="anchored" data-anchor-id="checking-data-quality-temperature">Checking data quality (Temperature)</h4>
<p>Similarly to Occurence Data, we will be using <code>visdat</code> library to check for data type errors</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots98" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots98-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;3: vis_dat() results of temperature</figcaption>
</figure>
</div>
</div>
</div>
<p>From the <a href="#fig-plots98">Figure&nbsp;3</a>, we can see that there are some NAs in <code>prcp</code>, <code>tmax</code>, and <code>tmin</code> columns. These empty data observations will then be removed accordingly.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots97" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots97-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;4: vis_guess() results of temperature</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-plots97">Figure&nbsp;4</a> shows that both <code>tmax</code> and <code>tmin</code> consists of both integers and double, which is reasonable as there might be some dates where the temperature is rounded up to the whole numbers. Moreover, this is rounding up is neglectable to us since we are not interested in such precision in temperature measurements. Some NAs were carried over fromt the previous vis_dat() results, which will be removed as they lack the necessary data from further analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>modified_temperature <span class="ot">&lt;-</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  temperature <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(modified_temperature, <span class="at">file =</span> (<span class="st">"data/temperature.rda"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The modified temperature data has been updated.</p>
</section>
</section>
<section id="tourism-data-1" class="level3">
<h3 class="anchored" data-anchor-id="tourism-data-1">Tourism Data</h3>
<p>As we will analyse the correlation between Tourism and Occurence (sightings), it will be best to join these two datasets. By joining these two datasets, we will be able to perform temporal and spatial analysis. Temporal and spatial analysis will be helpful to perform since it will reveal seasonal variation, long-term trends, short-term fluctuations, identifying hotspots, and causality.</p>
<section id="join-the-tourism-data-with-occurences-data" class="level4">
<h4 class="anchored" data-anchor-id="join-the-tourism-data-with-occurences-data">Join the Tourism Data with Occurences Data</h4>
<p>To join these two datasets, we are planning to use the spatial and temporal data that is contained in each dataset as the join condition. We are going to start the preparation for temporal variables before we move to spatial variables. Hence, in the next section the order will be temporal then spatial.</p>
<section id="preparation-for-the-temporal-data" class="level5">
<h5 class="anchored" data-anchor-id="preparation-for-the-temporal-data">Preparation for the Temporal Data</h5>
<p>The temporal variables between Occurences and Tourism data are represented by <code>eventDate</code> and <code>Quarter</code> variables, respectively. As both of these variables are in different format, we are going to transform one of them to enable the join process later. In this case, we are going to break down the <code>eventDate</code> variable into year &amp; quarter format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>weeping_mulla_mulla <span class="ot">&lt;-</span> weeping_mulla_mulla <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">mutate</span>(<span class="at">Quarter =</span> <span class="fu">paste</span>(<span class="st">"Q"</span>, lubridate<span class="sc">::</span><span class="fu">quarter</span>(eventDate), <span class="at">sep =</span> <span class="st">""</span>), </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">Year_Quarter =</span> tsibble<span class="sc">::</span><span class="fu">yearquarter</span>(eventDate)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preparation-for-the-spatial-data" class="level5">
<h5 class="anchored" data-anchor-id="preparation-for-the-spatial-data">Preparation for the Spatial Data</h5>
<p>As we know, the spatial variables between Tourism and Occurences data are presented by <code>Region</code> and <code>longitude</code> &amp; <code>latitude</code>, respectively. It is not possible to just join the data based on the value of these variables, so some data transformations are needed. Looking at the extraction code (given) for Tourism data and researching TRA’s website <a href="https://www.tra.gov.au/en/regional/tourism-regions.html">here</a>, we have got the idea that <code>Region</code> variable is the area level of the Statistical Area 2 (SA2). The SA2 is part of the main structure of the Australian Statistical Geography Standard (ASGS) Edition 3, meaning we can use its shapefile and extract the geometry of every region in Australia (which contain longitude &amp; latitude values). We will match the <code>geometry</code> in the SA2 data with <code>longitude</code> &amp; <code>latitude</code> in the Occurences dataset to get the SA2 region name of each sighting. The code below will provide the step-by-step of the extraction process.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converting Occurences data to a sf object</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>wmm_sf <span class="ot">&lt;-</span> weeping_mulla_mulla <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">crs =</span> <span class="fu">st_crs</span>(<span class="st">"WGS84"</span>))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Joining</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="do">## some points are out of the polygon, lets filter out so we get only points in the polygon</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>wmm_region <span class="ot">&lt;-</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_join</span>(AU_region, wmm_sf, <span class="at">left =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span>  <span class="co"># spatial join to get intersection of points and poly</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(region), <span class="co"># get only the points (sightings) that fall in the polygon (tourism region)</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(eventDate)) <span class="co"># filter out the NA values that represents mismatch geometry with Occurences data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="join-temporal-and-spatial-data" class="level5">
<h5 class="anchored" data-anchor-id="join-temporal-and-spatial-data">Join Temporal and Spatial Data</h5>
<p>Now, our Occurence data has matching region name with the region in the Tourism data, we also have transformed the format for temporal variables. Finally, We can start joining the temporal and spatial variables between these two datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Finalising joined occurences &amp; tourism weeping mulla mulla data</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>wmm_tourism <span class="ot">&lt;-</span> wmm_region <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                <span class="fu">left_join</span>(tourism, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"region"</span> <span class="ot">=</span> <span class="st">"Region"</span>, <span class="st">"Year_Quarter"</span> <span class="ot">=</span> <span class="st">"Quarter"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Purpose), <span class="co">#removing unmatch quarter</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                       <span class="sc">!</span>Purpose <span class="sc">==</span> <span class="st">"Total"</span>) <span class="sc">%&gt;%</span> <span class="co">#removing summarised number </span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>                <span class="fu">select</span>(<span class="sc">!</span><span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">7</span><span class="sc">:</span><span class="dv">9</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">group_by_all</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">summarise</span>(<span class="at">sightings_tot =</span> <span class="fu">n</span>())</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Dropping `geometry` for non-spatial related analysis</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>wmm_tourism_dg <span class="ot">&lt;-</span> wmm_tourism <span class="sc">%&gt;%</span> </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">st_drop_geometry</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory data analysis</h2>
<section id="the-analysis-of-our-expectations" class="level3">
<h3 class="anchored" data-anchor-id="the-analysis-of-our-expectations">The Analysis of Our Expectations</h3>
<p>In this section, we are going to analyse the data based on the expectations that we have set earlier in the report. We will answer those expectations through visual representation in order to help faster the process of understanding. Each of the analysis will be completed with discussion points that extracted from our analysis.</p>
<section id="spatial-expectation" class="level4">
<h4 class="anchored" data-anchor-id="spatial-expectation">Spatial expectation</h4>
<p>To evaluate the spatial distribution of the species, a method involving the use of a map to pinpoint locations was employed. This was achieved by utilising the <code>spData</code> package in conjunction with its <code>world</code> data.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Weeping Mulla Mulla Sightings Across Australia</figcaption>
</figure>
</div>
</div>
</div>
<p>The initial expectation was that the majority of sightings would be concentrated in Western Australia (<a href="#fig-plots3">Figure&nbsp;5</a>).</p>
<p>The map displaying the sightings below validates the initial hypothesis. However, it also reveals a significant number of sightings in the Northern Territory.</p>
<p>Most of the sightings are clustered in the northern regions of Western Australia, aligning with expectations. Notably, there are no sightings in the southern areas of Western Australia, including the city of Perth.</p>
</section>
<section id="temporal-expectation" class="level4">
<h4 class="anchored" data-anchor-id="temporal-expectation">Temporal expectation</h4>
<p>To assess the temporal occurrences of the species, the same method of using a map to pinpoint locations was employed. However, an additional step was introduced, involving the segmentation of the data by month to distribute the results throughout the year.</p>
<p>The initial expectation was that the Weeping Mulla Mulla would exhibit a higher frequency of observations from March to October (“Active” months).</p>
<p>The map (<a href="#fig-plots4">Figure&nbsp;6</a>) displaying the sightings by month validates this initial hypothesis, as there are fewer data points on the map in January and February, as well as in November and December.</p>
<p>Interestingly, a new insight emerges when the data is segmented by month. The previous map showed the regions where observations were most frequent, namely Western Australia and the Northern Territory. Now, when the data is subset by month, it becomes apparent that these two regions remain the primary clusters.</p>
<div class="cell" data-layout-align="center" data-fig-heigth="6">
<div class="cell-output-display">
<div id="fig-plots4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots4-1.png" class="img-fluid figure-img" width="1152"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Weeping Mulla Mulla Sightings By Month</figcaption>
</figure>
</div>
</div>
</div>
<p>To test the validity of our visual inference, we decided to employ <code>nullabor</code> null plots. Our hypotheses are as follows:</p>
<ul>
<li><span class="math inline">\(H_0:\)</span> There is no difference in the distribution of geographical points between the “Active” months and the “Others” months.</li>
<li><span class="math inline">\(H_1:\)</span> There is a difference in the distribution of geographical points between the “Active” months and the “Others” months.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots5-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Weeping Mulla Mulla Sightings Null Plots</figcaption>
</figure>
</div>
</div>
</div>
<p>We have given the null plots (<a href="#fig-plots5">Figure&nbsp;7</a>) to around 14 friends and only one of them picked the true plot at 16. This equates to the p-values below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pvisual</span>(<span class="dv">1</span>,<span class="dv">14</span>,<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     x simulated    binom
[1,] 1    0.4619 0.512325</code></pre>
</div>
</div>
<p><code>x simulated</code> shows 0.4612 and <code>binom</code> shows 0.512325 - both are above the threshold 0.05, which means that we fail to reject the null hypothesis in favor of the alternative hypothesis. Consequently, we are 95% confident that the selection of the true plot is by chance and there is no association between the combinations of <code>longitude</code> and <code>latitude</code> for different <code>Month</code> periods (“<em>Active</em>” and “<em>Others</em>”). This means that the Weeping Mulla Mulla can still be found outside of their active months without being in specific area.</p>
</section>
<section id="trend-expectation" class="level4">
<h4 class="anchored" data-anchor-id="trend-expectation">Trend expectation</h4>
<p>Since the data relies on human observation, it was anticipated that there might have been fewer sightings due to a lack of reporting.</p>
<p>By employing a simple method of plotting the number of observations against the years using a histogram (<a href="#fig-plots6">Figure&nbsp;8</a>), it can be seen that there was no indication of reduced observations during the COVID-19 years from 2000 to 2021. In fact, 2021 recorded the second-highest number of observations for the species.</p>
<p>Nevertheless, an interesting new observation stands out - a significant spike in sightings occurred in 2015. This spike was the highest, surpassing even the sightings in 2021, with 108 observations compared to 34, which is more than three times as many.</p>
<p>Currently, there are no findings that can explain this phenomenon. Given that the years after 2015 usually saw much higher reported sightings as compared to the previous, we hypothesize that this effect is due to the proliferation of internet-of-things, allowing sightings to be reported with greater ease and more reliable reporting platforms/databanks.</p>
<div class="cell" data-layout-align="center">
<div id="fig-plots6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-f3dbf6ca4045e6e889e5" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-f3dbf6ca4045e6e889e5">{"x":{"data":[{"orientation":"v","width":0.90000000000009095,"base":0,"x":[1987],"y":[1],"text":"Year: 1987<br />n:   1<br />as.factor(Year): 1987","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"1987","legendgroup":"1987","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[1988],"y":[8],"text":"Year: 1988<br />n:   8<br />as.factor(Year): 1988","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"1988","legendgroup":"1988","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[1989],"y":[1],"text":"Year: 1989<br />n:   1<br />as.factor(Year): 1989","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"1989","legendgroup":"1989","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[1993],"y":[12],"text":"Year: 1993<br />n:  12<br />as.factor(Year): 1993","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"1993","legendgroup":"1993","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[1994],"y":[2],"text":"Year: 1994<br />n:   2<br />as.factor(Year): 1994","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"1994","legendgroup":"1994","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[1995],"y":[2],"text":"Year: 1995<br />n:   2<br />as.factor(Year): 1995","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"1995","legendgroup":"1995","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[1996],"y":[3],"text":"Year: 1996<br />n:   3<br />as.factor(Year): 1996","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"1996","legendgroup":"1996","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[1998],"y":[1],"text":"Year: 1998<br />n:   1<br />as.factor(Year): 1998","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"1998","legendgroup":"1998","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2001],"y":[1],"text":"Year: 2001<br />n:   1<br />as.factor(Year): 2001","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2001","legendgroup":"2001","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2004],"y":[13],"text":"Year: 2004<br />n:  13<br />as.factor(Year): 2004","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2004","legendgroup":"2004","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2005],"y":[1],"text":"Year: 2005<br />n:   1<br />as.factor(Year): 2005","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2005","legendgroup":"2005","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2006],"y":[1],"text":"Year: 2006<br />n:   1<br />as.factor(Year): 2006","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2006","legendgroup":"2006","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2007],"y":[2],"text":"Year: 2007<br />n:   2<br />as.factor(Year): 2007","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2007","legendgroup":"2007","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2008],"y":[3],"text":"Year: 2008<br />n:   3<br />as.factor(Year): 2008","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2008","legendgroup":"2008","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2009],"y":[4],"text":"Year: 2009<br />n:   4<br />as.factor(Year): 2009","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2009","legendgroup":"2009","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2010],"y":[3],"text":"Year: 2010<br />n:   3<br />as.factor(Year): 2010","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2010","legendgroup":"2010","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2012],"y":[6],"text":"Year: 2012<br />n:   6<br />as.factor(Year): 2012","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2012","legendgroup":"2012","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2013],"y":[2],"text":"Year: 2013<br />n:   2<br />as.factor(Year): 2013","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2013","legendgroup":"2013","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2015],"y":[108],"text":"Year: 2015<br />n: 108<br />as.factor(Year): 2015","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2015","legendgroup":"2015","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2016],"y":[31],"text":"Year: 2016<br />n:  31<br />as.factor(Year): 2016","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2016","legendgroup":"2016","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2017],"y":[11],"text":"Year: 2017<br />n:  11<br />as.factor(Year): 2017","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2017","legendgroup":"2017","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2018],"y":[3],"text":"Year: 2018<br />n:   3<br />as.factor(Year): 2018","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2018","legendgroup":"2018","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2019],"y":[12],"text":"Year: 2019<br />n:  12<br />as.factor(Year): 2019","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2019","legendgroup":"2019","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2020],"y":[9],"text":"Year: 2020<br />n:   9<br />as.factor(Year): 2020","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(139,26,26,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2020","legendgroup":"2020","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2021],"y":[34],"text":"Year: 2021<br />n:  34<br />as.factor(Year): 2021","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(139,26,26,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2021","legendgroup":"2021","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2022],"y":[20],"text":"Year: 2022<br />n:  20<br />as.factor(Year): 2022","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2022","legendgroup":"2022","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000009095,"base":0,"x":[2023],"y":[20],"text":"Year: 2023<br />n:  20<br />as.factor(Year): 2023","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"2023","legendgroup":"2023","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":40.182648401826491,"l":37.260273972602747},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Weeping Mulla Mulla Observations by Year","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[1984.7049999999999,2025.2950000000001],"tickmode":"array","ticktext":["1985","1995","2005","2015","2025"],"tickvals":[1985,1995,2005,2015,2025],"categoryorder":"array","categoryarray":["1985","1995","2005","2015","2025"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":true,"linecolor":"rgba(0,0,0,1)","linewidth":0.66417600664176002,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"y","title":{"text":"Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-5.4000000000000004,113.40000000000001],"tickmode":"array","ticktext":["0","30","60","90"],"tickvals":[0,30,60.000000000000007,90],"categoryorder":"array","categoryarray":["0","30","60","90"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":true,"linecolor":"rgba(0,0,0,1)","linewidth":0.66417600664176002,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"x","title":{"text":"Number of observations","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"297418972432":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"297418972432","visdat":{"297418972432":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<figcaption class="figure-caption">Figure&nbsp;8: Weeping Mulla Mulla Observations by Year</figcaption>
</figure>
</div>
</div>
</section>
<section id="seasonality-expectation" class="level4">
<h4 class="anchored" data-anchor-id="seasonality-expectation">Seasonality expectation</h4>
<p>To test whether our expectation that the Weeping Mulla Mulla becomes more active after rainfall seasons is accurate, we decided to plot the occurrences by month. While there are some indications from the previous <em>Temporal expectation</em> section, where June to August plots show considerably more observation points, we would like create a bar plot for a better visualization inference.</p>
<div class="cell" data-layout-align="center">
<div id="fig-plots7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-7ea328ba1b711520566b" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-7ea328ba1b711520566b">{"x":{"data":[{"orientation":"v","width":0.89999999999999991,"base":0,"x":[1],"y":[4],"text":"monthName: Jan<br />n:  4<br />as.factor(monthName): Jan","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Jan","legendgroup":"Jan","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000000013,"base":0,"x":[2],"y":[4],"text":"monthName: Feb<br />n:  4<br />as.factor(monthName): Feb","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Feb","legendgroup":"Feb","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000000036,"base":0,"x":[3],"y":[10],"text":"monthName: Mar<br />n: 10<br />as.factor(monthName): Mar","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Mar","legendgroup":"Mar","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000000036,"base":0,"x":[4],"y":[35],"text":"monthName: Apr<br />n: 35<br />as.factor(monthName): Apr","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Apr","legendgroup":"Apr","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000000036,"base":0,"x":[5],"y":[42],"text":"monthName: May<br />n: 42<br />as.factor(monthName): May","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"May","legendgroup":"May","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000000036,"base":0,"x":[6],"y":[20],"text":"monthName: Jun<br />n: 20<br />as.factor(monthName): Jun","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(197,153,178,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Jun","legendgroup":"Jun","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.90000000000000036,"base":0,"x":[7],"y":[21],"text":"monthName: Jul<br />n: 21<br />as.factor(monthName): Jul","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(197,153,178,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Jul","legendgroup":"Jul","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.89999999999999947,"base":0,"x":[8],"y":[59],"text":"monthName: Aug<br />n: 59<br />as.factor(monthName): Aug","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(197,153,178,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Aug","legendgroup":"Aug","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.89999999999999858,"base":0,"x":[9],"y":[79],"text":"monthName: Sep<br />n: 79<br />as.factor(monthName): Sep","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Sep","legendgroup":"Sep","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.89999999999999858,"base":0,"x":[10],"y":[37],"text":"monthName: Oct<br />n: 37<br />as.factor(monthName): Oct","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Oct","legendgroup":"Oct","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.89999999999999858,"base":0,"x":[11],"y":[2],"text":"monthName: Nov<br />n:  2<br />as.factor(monthName): Nov","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Nov","legendgroup":"Nov","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"orientation":"v","width":0.89999999999999858,"base":0,"x":[12],"y":[1],"text":"monthName: Dec<br />n:  1<br />as.factor(monthName): Dec","type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(127,127,127,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"name":"Dec","legendgroup":"Dec","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":40.182648401826491,"l":37.260273972602747},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Weeping Mulla Mulla Observations by Month","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.40000000000000002,12.6],"tickmode":"array","ticktext":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"tickvals":[1,2,3,4.0000000000000009,5,6,7.0000000000000009,8,9,10,11,12],"categoryorder":"array","categoryarray":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":true,"linecolor":"rgba(0,0,0,1)","linewidth":0.66417600664176002,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"y","title":{"text":"Month","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-3.9500000000000002,82.950000000000003],"tickmode":"array","ticktext":["0","20","40","60","80"],"tickvals":[0,20,39.999999999999993,60,80],"categoryorder":"array","categoryarray":["0","20","40","60","80"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":true,"linecolor":"rgba(0,0,0,1)","linewidth":0.66417600664176002,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"x","title":{"text":"Number of observations","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"29747c535afb":{"x":{},"y":{},"fill":{},"type":"bar"}},"cur_data":"29747c535afb","visdat":{"29747c535afb":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<figcaption class="figure-caption">Figure&nbsp;9: Weeping Mulla Mulla Observations by Month (Bars)</figcaption>
</figure>
</div>
</div>
<p>Interestingly, we observe decreased sightings during June and July while August has the highest sighting occurrences (<a href="#fig-plots7">Figure&nbsp;9</a>). March marks the start of the blooming cycle with April and May being the autumn season in Western Australia (Tourism Australia n.&nbsp;d.), which has occasional showers. This explains the large rise in sightings for these months. However, the main raining events (June to August) saw significantly lower occurrences - we believe this is due to thunderstorms and flooding, preventing casual observers to stumble upon these plants. Only August has high sighting occurrences, as the end of winter has milder downpours.</p>
</section>
<section id="habitat-expectation" class="level4">
<h4 class="anchored" data-anchor-id="habitat-expectation">Habitat expectation</h4>
<p>Given that the Weeping Mulla Mulla prefers stony and sandy environments, we expect the plants to be sighted near areas with freshwater such as river banks. Moreover, observations by travelers might be more likely to be located near and/or on the way to a water source. To test our this expectation, we deploy a <code>leaflet</code> map, which displays geographical features such as subsurface water, creeks, lakes, and rivers.</p>
<div class="cell" data-layout-align="center">
<div id="fig-plots8" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div class="leaflet html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-ee204ae1ce74d54f4649" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-ee204ae1ce74d54f4649">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["Esri.DeLorme",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircleMarkers","args":[[-24.92637,-24.88139,-24.831,-24.831,-23.635464,-23.347663,-23.343507,-23.249701,-22.98952,-22.968522,-22.915269,-22.884576,-22.721379,-22.703481,-22.603638,-22.602916,-22.596658,-22.563828,-22.52959,-22.489682,-22.489275,-22.488925,-22.476578,-22.4755,-22.473027,-22.471344,-22.469722,-22.463235,-22.452836,-22.388645,-22.388624,-22.257155,-22.16544,-21.97379,-21.945856,-21.870746,-21.838707,-21.733533,-21.72664,-21.617833,-21.617833,-21.614884,-21.582853,-21.579594,-21.576002,-21.574056,-21.57277,-21.541103,-21.511828,-21.481834,-21.418448,-21.331,-21.312727,-21.278442,-21.205871,-21.204668,-21.177544,-21.173701,-21.16261,-21.15763,-21.126622,-21.10231,-21.101738,-21.050878,-21.048372,-21.048274,-21.043195,-21.032429,-21.019396,-21.015883,-21.009417,-21.009199,-21.003011,-21.001455,-20.997189,-20.99717,-20.994475,-20.994224,-20.991712,-20.988414,-20.988057,-20.985577,-20.982557,-20.982205,-20.97943,-20.976355,-20.97481,-20.972174,-20.969205,-20.965197,-20.963884,-20.960817,-20.960405,-20.960334,-20.958574,-20.95829,-20.956299,-20.955891,-20.9554,-20.954385,-20.954385,-20.951821,-20.950134,-20.949971,-20.94859,-20.945884,-20.945597,-20.944745,-20.939384,-20.93931,-20.93329,-20.930955,-20.926775,-20.92642,-20.921444,-20.916348,-20.914099,-20.910702,-20.908404,-20.907149,-20.905168,-20.903123,-20.900206,-20.892721,-20.889404,-20.888558,-20.888291,-20.881672,-20.866842,-20.866054,-20.862992,-20.848869,-20.844714,-20.838397,-20.838172,-20.836,-20.83482,-20.833808,-20.828179,-20.822859,-20.819184,-20.817223,-20.808104,-20.799552,-20.793407,-20.793407,-20.788768,-20.770423,-20.58866,-20.585863,-20.449183,-20.409496,-20.226387,-20.0766,-20.017908,-20.00436,-20,-19.991705,-19.952702,-19.900764,-19.842912,-19.82652,-19.795638,-19.794451,-19.791679,-19.791318,-19.786672,-19.782027,-19.777635,-19.776906,-19.776696,-19.776375,-19.77336,-19.77206,-19.768752,-19.764023,-19.761428,-19.761268,-19.760729,-19.760633,-19.760527,-19.759499,-19.759389,-19.759276,-19.759269,-19.759222,-19.75542,-19.754155,-19.753509,-19.751575,-19.746024,-19.744552,-19.744412,-19.739859,-19.736255,-19.735764,-19.732994,-19.731928,-19.729218,-19.724622,-19.721289,-19.721283,-19.721239,-19.721047,-19.721043,-19.721024,-19.720985,-19.720983,-19.717655,-19.716908,-19.70119,-19.692061,-19.67612,-19.650208,-19.63742,-19.616018,-19.610897,-19.609871,-19.60759,-19.60758,-19.60755,-19.607541,-19.607528,-19.607499,-19.607491,-19.607481,-19.607456,-19.607383,-19.579463,-19.574444,-19.435337,-19.427922,-19.32684,-19.3202,-19.31884,-19.27083,-19.2545,-19.2541,-19.195281,-19.173118,-19.042738,-19.042377,-19.039827,-18.90047,-18.8978,-18.828771,-18.79834,-18.754633,-18.749842,-18.748925,-18.748544,-18.748544,-18.748322,-18.747823,-18.747411,-18.73309,-18.72936,-18.63607,-18.625522,-18.604107,-18.601575,-18.533247,-18.522517,-18.518889,-18.518611,-18.51124,-18.504358,-18.488,-18.465887,-18.443251,-18.42128,-18.395194,-18.360472,-18.354122,-18.335,-18.332312,-18.224822,-18.220556,-18.08586,-17.982737,-17.97502,-17.971977,-17.935497,-17.7089,-17.691004,-17.67596,-17.64086,-17.63523,-17.524972,-17.39883,-17.39372,-17.374737,-17.35674,-17.35503,-17.32864,-17.32629,-17.120244,-16.970676,-16.94958,-16.92838,-16.855777,-16.37848,-16.029135,-16.028118,-15.965,-15.860867,-15.848218,-15.67655,-15.66423,-15.639855,-15.606519,-15.555047,-15.452222,-15.14837],[131.167,129.20921,128.911,128.911,132.739944,119.727495,119.744828,119.57028,118.922125,119.393121,118.254643,119.173191,118.329345,117.761979,118.112712,118.118161,118.100861,118.485642,118.457322,118.483837,118.73587,118.735313,118.552441,118.5516,118.550035,118.557264,118.555556,118.183853,118.365023,118.262928,118.262913,117.985955,121.674438,115.644651,118.686019,115.610191,115.639928,120.442313,118.525279,121.576438,121.576438,134.110543,117.093247,117.067147,118.82902,133.843326,117.21627,117.056997,134.156373,133.83388,117.153164,117.244,130.867158,118.402345,119.72295,119.727428,134.307554,134.268232,134.296845,134.309756,134.241943,119.766164,119.16566,118.617867,134.440771,134.41952,134.483465,134.428233,118.903261,134.326383,134.325027,134.343223,134.327259,134.338282,134.290878,134.27761,134.35363,134.27977,134.174107,134.310142,134.287092,134.299004,134.279172,134.26634,134.274617,134.313131,134.280335,134.263965,134.296888,134.226754,134.363823,134.243302,134.330672,134.356816,134.195354,134.275094,134.365,134.357336,134.277638,134.174091,134.174091,134.221888,134.354494,134.258937,134.246874,134.241146,134.254467,134.365491,134.199256,134.208604,134.244065,134.230853,134.202083,134.190112,134.262982,134.366521,134.213804,134.206187,134.225074,134.215456,134.24911,134.214188,134.242606,134.327235,134.21349,134.246326,134.41745,134.227788,134.322598,134.226521,134.223775,134.26409,134.232025,117.833305,117.833886,119.561,134.268048,134.223059,134.23881,134.246982,134.243129,134.215022,134.231892,134.208985,134.109889,134.109889,134.126687,116.891045,134.278736,134.263961,119.997503,134.244157,119.58767,136.9164,119.960789,137.192975,136,136.644527,136.493115,129.358895,136.156425,130.42548,133.90063,133.840098,133.900447,133.900478,133.900329,133.900189,133.900057,133.855907,133.841543,133.84627,133.899914,133.93166,133.899803,133.894958,133.885823,133.876214,133.866664,133.871561,133.861884,133.902758,133.917361,133.907579,133.912371,133.922526,133.89769,133.843252,133.925227,133.895378,133.941376,133.889271,133.916517,133.914009,133.844622,133.911852,133.881774,133.909664,133.878947,133.90584,133.960553,133.894159,133.951189,133.89888,133.88951,133.979339,133.884757,133.9037,121.566642,133.91218,129.79075,133.881448,129.77735,133.851343,129.61747,133.861222,134.20883,134.209926,133.814212,133.789584,133.819171,133.804058,133.808911,133.765796,133.853439,133.84338,133.854699,133.760743,134.199027,130.765556,135.429745,135.393507,135.22021,134.851295,135.21801,130.63646,130.61571,130.6301,126.861435,127.789748,121.66641,121.667664,121.667642,131.60233,129.6975,126.522488,126.533373,136.805083,126.107994,126.110043,126.108503,126.108878,126.108758,126.108592,136.871472,130.32092,126.85851,129.6217,136.642528,121.96645,137.113133,136.595361,122.021237,136.954444,136.954247,127.567228,136.623056,136.812025,133.861088,133.608311,122.112595,135.8687,135.751756,135.892792,130.613056,133.804075,134.345065,127.673889,132.68062,125.227565,133.6805,134.805647,130.824873,131.5031,134.761084,133.62404,133.60361,133.58891,135.696785,133.43896,130.38531,133.439422,130.57042,130.40294,130.22855,133.43811,134.047839,130.308192,130.13693,130.14078,133.455311,134.7343,130.777197,130.783748,127.932,127.947344,131.168776,131.31776,131.32181,130.867289,131.109015,131.288522,129.321111,132.87892],10,null,null,{"interactive":true,"className":"","stroke":false,"color":"#5b9b2e","weight":5,"opacity":0.5,"fill":true,"fillColor":"#5b9b2e","fillOpacity":0.1},null,null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"setView":[[-21.833,128.583],5,[]],"limits":{"lat":[-24.92637,-15.14837],"lng":[115.610191,137.192975]}},"evals":[],"jsHooks":[]}</script>
<figcaption class="figure-caption">Figure&nbsp;10: Habitat Map Of Weeping Mulla Mulla Distribution</figcaption>
</figure>
</div>
</div>
<p>The map is seen in the <a href="#fig-plots8">Figure&nbsp;10</a>, but due to the zoom level, we could not see the water body features of the map; Therefore, we decided to investigate a cluster of sightings near Ali Curung.</p>
<div class="cell" data-layout-align="center">
<div id="fig-plots9" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div class="leaflet html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-533a8b1dc41a35bd4292" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-533a8b1dc41a35bd4292">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["Esri.DeLorme",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircleMarkers","args":[[-24.92637,-24.88139,-24.831,-24.831,-23.635464,-23.347663,-23.343507,-23.249701,-22.98952,-22.968522,-22.915269,-22.884576,-22.721379,-22.703481,-22.603638,-22.602916,-22.596658,-22.563828,-22.52959,-22.489682,-22.489275,-22.488925,-22.476578,-22.4755,-22.473027,-22.471344,-22.469722,-22.463235,-22.452836,-22.388645,-22.388624,-22.257155,-22.16544,-21.97379,-21.945856,-21.870746,-21.838707,-21.733533,-21.72664,-21.617833,-21.617833,-21.614884,-21.582853,-21.579594,-21.576002,-21.574056,-21.57277,-21.541103,-21.511828,-21.481834,-21.418448,-21.331,-21.312727,-21.278442,-21.205871,-21.204668,-21.177544,-21.173701,-21.16261,-21.15763,-21.126622,-21.10231,-21.101738,-21.050878,-21.048372,-21.048274,-21.043195,-21.032429,-21.019396,-21.015883,-21.009417,-21.009199,-21.003011,-21.001455,-20.997189,-20.99717,-20.994475,-20.994224,-20.991712,-20.988414,-20.988057,-20.985577,-20.982557,-20.982205,-20.97943,-20.976355,-20.97481,-20.972174,-20.969205,-20.965197,-20.963884,-20.960817,-20.960405,-20.960334,-20.958574,-20.95829,-20.956299,-20.955891,-20.9554,-20.954385,-20.954385,-20.951821,-20.950134,-20.949971,-20.94859,-20.945884,-20.945597,-20.944745,-20.939384,-20.93931,-20.93329,-20.930955,-20.926775,-20.92642,-20.921444,-20.916348,-20.914099,-20.910702,-20.908404,-20.907149,-20.905168,-20.903123,-20.900206,-20.892721,-20.889404,-20.888558,-20.888291,-20.881672,-20.866842,-20.866054,-20.862992,-20.848869,-20.844714,-20.838397,-20.838172,-20.836,-20.83482,-20.833808,-20.828179,-20.822859,-20.819184,-20.817223,-20.808104,-20.799552,-20.793407,-20.793407,-20.788768,-20.770423,-20.58866,-20.585863,-20.449183,-20.409496,-20.226387,-20.0766,-20.017908,-20.00436,-20,-19.991705,-19.952702,-19.900764,-19.842912,-19.82652,-19.795638,-19.794451,-19.791679,-19.791318,-19.786672,-19.782027,-19.777635,-19.776906,-19.776696,-19.776375,-19.77336,-19.77206,-19.768752,-19.764023,-19.761428,-19.761268,-19.760729,-19.760633,-19.760527,-19.759499,-19.759389,-19.759276,-19.759269,-19.759222,-19.75542,-19.754155,-19.753509,-19.751575,-19.746024,-19.744552,-19.744412,-19.739859,-19.736255,-19.735764,-19.732994,-19.731928,-19.729218,-19.724622,-19.721289,-19.721283,-19.721239,-19.721047,-19.721043,-19.721024,-19.720985,-19.720983,-19.717655,-19.716908,-19.70119,-19.692061,-19.67612,-19.650208,-19.63742,-19.616018,-19.610897,-19.609871,-19.60759,-19.60758,-19.60755,-19.607541,-19.607528,-19.607499,-19.607491,-19.607481,-19.607456,-19.607383,-19.579463,-19.574444,-19.435337,-19.427922,-19.32684,-19.3202,-19.31884,-19.27083,-19.2545,-19.2541,-19.195281,-19.173118,-19.042738,-19.042377,-19.039827,-18.90047,-18.8978,-18.828771,-18.79834,-18.754633,-18.749842,-18.748925,-18.748544,-18.748544,-18.748322,-18.747823,-18.747411,-18.73309,-18.72936,-18.63607,-18.625522,-18.604107,-18.601575,-18.533247,-18.522517,-18.518889,-18.518611,-18.51124,-18.504358,-18.488,-18.465887,-18.443251,-18.42128,-18.395194,-18.360472,-18.354122,-18.335,-18.332312,-18.224822,-18.220556,-18.08586,-17.982737,-17.97502,-17.971977,-17.935497,-17.7089,-17.691004,-17.67596,-17.64086,-17.63523,-17.524972,-17.39883,-17.39372,-17.374737,-17.35674,-17.35503,-17.32864,-17.32629,-17.120244,-16.970676,-16.94958,-16.92838,-16.855777,-16.37848,-16.029135,-16.028118,-15.965,-15.860867,-15.848218,-15.67655,-15.66423,-15.639855,-15.606519,-15.555047,-15.452222,-15.14837],[131.167,129.20921,128.911,128.911,132.739944,119.727495,119.744828,119.57028,118.922125,119.393121,118.254643,119.173191,118.329345,117.761979,118.112712,118.118161,118.100861,118.485642,118.457322,118.483837,118.73587,118.735313,118.552441,118.5516,118.550035,118.557264,118.555556,118.183853,118.365023,118.262928,118.262913,117.985955,121.674438,115.644651,118.686019,115.610191,115.639928,120.442313,118.525279,121.576438,121.576438,134.110543,117.093247,117.067147,118.82902,133.843326,117.21627,117.056997,134.156373,133.83388,117.153164,117.244,130.867158,118.402345,119.72295,119.727428,134.307554,134.268232,134.296845,134.309756,134.241943,119.766164,119.16566,118.617867,134.440771,134.41952,134.483465,134.428233,118.903261,134.326383,134.325027,134.343223,134.327259,134.338282,134.290878,134.27761,134.35363,134.27977,134.174107,134.310142,134.287092,134.299004,134.279172,134.26634,134.274617,134.313131,134.280335,134.263965,134.296888,134.226754,134.363823,134.243302,134.330672,134.356816,134.195354,134.275094,134.365,134.357336,134.277638,134.174091,134.174091,134.221888,134.354494,134.258937,134.246874,134.241146,134.254467,134.365491,134.199256,134.208604,134.244065,134.230853,134.202083,134.190112,134.262982,134.366521,134.213804,134.206187,134.225074,134.215456,134.24911,134.214188,134.242606,134.327235,134.21349,134.246326,134.41745,134.227788,134.322598,134.226521,134.223775,134.26409,134.232025,117.833305,117.833886,119.561,134.268048,134.223059,134.23881,134.246982,134.243129,134.215022,134.231892,134.208985,134.109889,134.109889,134.126687,116.891045,134.278736,134.263961,119.997503,134.244157,119.58767,136.9164,119.960789,137.192975,136,136.644527,136.493115,129.358895,136.156425,130.42548,133.90063,133.840098,133.900447,133.900478,133.900329,133.900189,133.900057,133.855907,133.841543,133.84627,133.899914,133.93166,133.899803,133.894958,133.885823,133.876214,133.866664,133.871561,133.861884,133.902758,133.917361,133.907579,133.912371,133.922526,133.89769,133.843252,133.925227,133.895378,133.941376,133.889271,133.916517,133.914009,133.844622,133.911852,133.881774,133.909664,133.878947,133.90584,133.960553,133.894159,133.951189,133.89888,133.88951,133.979339,133.884757,133.9037,121.566642,133.91218,129.79075,133.881448,129.77735,133.851343,129.61747,133.861222,134.20883,134.209926,133.814212,133.789584,133.819171,133.804058,133.808911,133.765796,133.853439,133.84338,133.854699,133.760743,134.199027,130.765556,135.429745,135.393507,135.22021,134.851295,135.21801,130.63646,130.61571,130.6301,126.861435,127.789748,121.66641,121.667664,121.667642,131.60233,129.6975,126.522488,126.533373,136.805083,126.107994,126.110043,126.108503,126.108878,126.108758,126.108592,136.871472,130.32092,126.85851,129.6217,136.642528,121.96645,137.113133,136.595361,122.021237,136.954444,136.954247,127.567228,136.623056,136.812025,133.861088,133.608311,122.112595,135.8687,135.751756,135.892792,130.613056,133.804075,134.345065,127.673889,132.68062,125.227565,133.6805,134.805647,130.824873,131.5031,134.761084,133.62404,133.60361,133.58891,135.696785,133.43896,130.38531,133.439422,130.57042,130.40294,130.22855,133.43811,134.047839,130.308192,130.13693,130.14078,133.455311,134.7343,130.777197,130.783748,127.932,127.947344,131.168776,131.31776,131.32181,130.867289,131.109015,131.288522,129.321111,132.87892],10,null,null,{"interactive":true,"className":"","stroke":false,"color":"#5b9b2e","weight":5,"opacity":0.5,"fill":true,"fillColor":"#5b9b2e","fillOpacity":0.5},null,null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"setView":[[-20.9358,134.2996],10,[]],"limits":{"lat":[-24.92637,-15.14837],"lng":[115.610191,137.192975]}},"evals":[],"jsHooks":[]}</script>
<figcaption class="figure-caption">Figure&nbsp;11: Habitat Map Of Weeping Mulla Mulla Distribution(Ali Curung, Barkly)</figcaption>
</figure>
</div>
</div>
<p>Based on the map above (<a href="#fig-plots9">Figure&nbsp;11</a>), we can see that the main cluster of Weeping Mulla Mulla does not live near a water source, which is different from what we expected. This suggests that the plant is dependent on rain, meaning that high precipitation periods might lead to higher sightings. It is also interesting to see that these sightings were near the National 87 road, implying that these reports were made by passersby.</p>
</section>
</section>
<section id="the-weather-analysis" class="level3">
<h3 class="anchored" data-anchor-id="the-weather-analysis">The Weather Analysis</h3>
<p>This section will cover the correlation between weather environment to the sightings of Weeping Mulla Mulla. We are going to analyse if there is any actual relationship between these two variables. We aim to spot the behaviour of Weeping Mulla Mulla towards environment condition. Let’s find out!</p>
<section id="precipitation-and-sighting-annually" class="level4">
<h4 class="anchored" data-anchor-id="precipitation-and-sighting-annually">Precipitation and sighting annually</h4>
<p>The additional data from the <code>tenant creek airport</code> weather station allows us to investigate the relation between precipitation and sighting directly, resulting in the graph below which visualizes annual average rainfall and annual sightings.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots10" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots10-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;12: Sighting Count and Average Precipitation by Year (Barkly and Tennant Creek Station)</figcaption>
</figure>
</div>
</div>
</div>
<p>From the <a href="#fig-plots10">Figure&nbsp;12</a>, we can see there are multiple gaps in the sighting of the Weeping Mulla Mulla from 2004 to 2023. This inconsistency can be explained by the lack of popularity of our plant species. As addressed above in the <strong>Trend expectation</strong> section, 2015 saw an abnormally high sighting count, despite a normal annual average precipitation figure for that year, especially when there were no sighting records in 2013-2014. We can hypothesize a delayed effect of plant sightings where years with decreasing rainfall will be accompanied by sightings when the annual average precipitation begins to trend upward. For instance, 2006 - 2007 saw a decreasing trend in rainfall without any plant sightings; However, 2008 saw new reported sightings, as well as the start of increasing precipitation trend from 2008 to 2011. Another example is when the downward trend from 2011 to 2013 saw dwindling sightings with increasing rainfall but from 2015 onwards, sightings were much higher and there were fewer gaps in annual sightings. Perhaps this is due to preference for dry weather of the plants; therefore, decreasing precips allow the Weeping Mulla Mulla to thrive better in constrast to being overwatered in wetter years.</p>
</section>
<section id="temperature-and-sightings" class="level4">
<h4 class="anchored" data-anchor-id="temperature-and-sightings">Temperature and sightings</h4>
<p>Since the rainfall data did not signify any concrete answers, we decided to also investigate the daily average temperature and whether that date has a reported sighting. This is to determine at what average temperature that sighting is likely to be made.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots11" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots11-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;13: Daily Mean Temperature and Sightings (Barkly) (2004-2023)</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Discussion</strong></p>
<p><a href="#fig-plots11">Figure&nbsp;13</a> depicts that, even when the data ranges from 2004 to 2023, there are very little reported sightings of the Weeping Mulla Mulla in <em>Barkly</em>. Nonetheless, we can observe that most of the years have very similar seasonality trend for average temperatures; thus, we decided to investigate 2015 as it has the most reported sightings.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots12" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots12-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;14: Daily Mean Temperature, Sighting, Plant Active Window (Barkly, 2015)</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Discussion</strong></p>
<p>By narrowing it down to <code>2015</code>, we recognize that most of the sightings happened in the later half of the year, specifically when the weather begins to get warmer but not during the warmest days (<a href="#fig-plots12">Figure&nbsp;14</a>). While most of the observations were reported within the “Active” months of the flower, it is interesting to see that March to early July saw no reported sightings. We believe that lack of observations is caused by lack of human observers rather than the plant’s blooming characteristics since we have explored this habit earlier in the <strong>Temporal expectation</strong> section. Additionally, it is intriguing to observe that the active months of the plant coincide with the transition from colder to warmer weather in the lower figure. We also consider the possibility that the mentality effect of <em>“the weather is getting warmer”</em> enables a greater inclination in people for outdoor ventures - increasing the sighting frequency of the plant.</p>
</section>
</section>
<section id="tourism-analysis" class="level3">
<h3 class="anchored" data-anchor-id="tourism-analysis">Tourism Analysis</h3>
<p>In this section, we aim to correlate the number of sightings of Weeping Mulla Mulla with the number of tourists in the area of the sightings. Is the number of sightings influenced by nearby tourism activities? Does the increasing number of visit resulted in increasing number of Weeping Mulla Mulla sightings? Let’s explore the data that we have to understand that.</p>
<p>By continuing our earlier observations, we will now focus on the area with the most recorded sightings, which, as mentioned in the previous section, is close to the Tennant Creek Airport weather station. By utilizing data from Australian Bureau of Statistics of SA2, we identified that Tennant Creek Airport is located in the region of Barkly, Northern Territory.</p>
<p>Therefore, our subsequent analysis will concentrate solely on the Barkly region.</p>
<section id="trend-of-tourist-over-time" class="level4">
<h4 class="anchored" data-anchor-id="trend-of-tourist-over-time">Trend of Tourist Over Time</h4>
<p>Before we dive deep into the correlation analysis of occurrences and tourism, we would like to explore the tourism data. It is important to profile this data first, as most of the time they provide a deeper understanding and can sharpen our analysis later. The chart below illustrates the trend of tourism in Barkly Region.</p>
<div class="cell" data-layout-align="center">
<div id="fig-plots13" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-a69ef61e0628b8d3ac27" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-a69ef61e0628b8d3ac27">{"x":{"data":[{"x":[10227,10317,10408,10500,10592,10682,10773,10865,10957,11048,11139,11231,11323,11413,11504,11596,11688,11778,11869,11961,12053,12143,12234,12326,12418,12509,12600,12692,12784,12874,12965,13057,13149,13239,13330,13422,13514,13604,13695,13787,13879,13970,14061,14153,14245,14335,14426,14518,14610,14700,14791,14883,14975,15065,15156,15248,15340,15431,15522,15614,15706,15796,15887,15979,16071,16161,16252,16344,16436,16526,16617,16709,16801,16892,16983,17075,17167,17257,17348,17440,17532,17622,17713,17805,17897,17987,18078,18170,18262,18353,18444,18536,18628,18718,18809,18901,18993,19083,19174,19266],"y":[12.4155444,6.6583392000000003,16.9211411,20.668097599999999,1.3019263000000001,13.1551525,7.4382830999999996,4.8567926999999997,7.5693857999999992,13.4665838,18.333327699999998,8.4638735,1.6603872,9.8777056000000005,12.3188681,32.515369900000003,4.8082595000000001,21.7829561,13.5715269,20.085029899999999,4.3352110000000001,11.512478999999999,37.7393833,7.2644865999999997,6.3604437000000003,8.7186328999999994,19.281862800000003,6.0375512000000002,6.5667805999999995,9.8268582999999996,26.6154127,0.71234039999999998,9.4936729999999994,8.1456940000000007,17.720699,6.3510990000000005,2.6778412,5.0403471,9.632867000000001,10.585517099999999,0.69735480000000005,10.9782212,19.320984800000002,2.2640463,0.73153520000000005,11.464822699999999,14.034418199999999,1.1207091,5.7055159999999994,4.9895716999999999,19.090405199999999,9.0994247999999995,1.9231902999999999,3.559571,36.5969281,5.0373280000000005,6.7601505,7.147062,16.005712899999999,7.9012293000000007,1.2050858,12.1302542,13.895526700000001,4.2642348999999999,3.7099403999999998,5.0991149999999994,23.650478700000001,10.856045099999999,1.3031109000000001,10.9236171,17.599579599999998,16.716481699999999,8.6217632999999996,14.526726400000001,28.109085399999998,11.294670400000001,8.7897198999999997,24.918258399999999,14.7132088,9.0363734000000004,0,23.903738600000001,13.7949632,21.404598499999999,6.0704411,13.945444800000001,25.444702100000001,10.0180881,6.4248418000000003,1.5258849999999999,5.6324325000000002,4.3808663000000001,1.9005300000000001,8.6356222999999996,14.570851899999999,2.3044030000000002,0,7.7686965000000008,18.970408899999999,5.6223744],"text":"","type":"scatter","mode":"lines","line":{"width":3.7795275590551185,"color":"rgba(69,139,116,0.5)","dash":"solid"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[10227,10317,10408,10500,10592,10682,10773,10865,10957,11048,11139,11231,11323,11413,11504,11596,11688,11778,11869,11961,12053,12143,12234,12326,12418,12509,12600,12692,12784,12874,12965,13057,13149,13239,13330,13422,13514,13604,13695,13787,13879,13970,14061,14153,14245,14335,14426,14518,14610,14700,14791,14883,14975,15065,15156,15248,15340,15431,15522,15614,15706,15796,15887,15979,16071,16161,16252,16344,16436,16526,16617,16709,16801,16892,16983,17075,17167,17257,17348,17440,17532,17622,17713,17805,17897,17987,18078,18170,18262,18353,18444,18536,18628,18718,18809,18901,18993,19083,19174,19266],"y":[12.4155444,6.6583392000000003,16.9211411,20.668097599999999,1.3019263000000001,13.1551525,7.4382830999999996,4.8567926999999997,7.5693857999999992,13.4665838,18.333327699999998,8.4638735,1.6603872,9.8777056000000005,12.3188681,32.515369900000003,4.8082595000000001,21.7829561,13.5715269,20.085029899999999,4.3352110000000001,11.512478999999999,37.7393833,7.2644865999999997,6.3604437000000003,8.7186328999999994,19.281862800000003,6.0375512000000002,6.5667805999999995,9.8268582999999996,26.6154127,0.71234039999999998,9.4936729999999994,8.1456940000000007,17.720699,6.3510990000000005,2.6778412,5.0403471,9.632867000000001,10.585517099999999,0.69735480000000005,10.9782212,19.320984800000002,2.2640463,0.73153520000000005,11.464822699999999,14.034418199999999,1.1207091,5.7055159999999994,4.9895716999999999,19.090405199999999,9.0994247999999995,1.9231902999999999,3.559571,36.5969281,5.0373280000000005,6.7601505,7.147062,16.005712899999999,7.9012293000000007,1.2050858,12.1302542,13.895526700000001,4.2642348999999999,3.7099403999999998,5.0991149999999994,23.650478700000001,10.856045099999999,1.3031109000000001,10.9236171,17.599579599999998,16.716481699999999,8.6217632999999996,14.526726400000001,28.109085399999998,11.294670400000001,8.7897198999999997,24.918258399999999,14.7132088,9.0363734000000004,0,23.903738600000001,13.7949632,21.404598499999999,6.0704411,13.945444800000001,25.444702100000001,10.0180881,6.4248418000000003,1.5258849999999999,5.6324325000000002,4.3808663000000001,1.9005300000000001,8.6356222999999996,14.570851899999999,2.3044030000000002,0,7.7686965000000008,18.970408899999999,5.6223744],"text":["Year & Quarter:  1998 Q1 <br>Total Trips ('000):  12.4155444","Year & Quarter:  1998 Q2 <br>Total Trips ('000):  6.6583392","Year & Quarter:  1998 Q3 <br>Total Trips ('000):  16.9211411","Year & Quarter:  1998 Q4 <br>Total Trips ('000):  20.6680976","Year & Quarter:  1999 Q1 <br>Total Trips ('000):  1.3019263","Year & Quarter:  1999 Q2 <br>Total Trips ('000):  13.1551525","Year & Quarter:  1999 Q3 <br>Total Trips ('000):  7.4382831","Year & Quarter:  1999 Q4 <br>Total Trips ('000):  4.8567927","Year & Quarter:  2000 Q1 <br>Total Trips ('000):  7.5693858","Year & Quarter:  2000 Q2 <br>Total Trips ('000):  13.4665838","Year & Quarter:  2000 Q3 <br>Total Trips ('000):  18.3333277","Year & Quarter:  2000 Q4 <br>Total Trips ('000):  8.4638735","Year & Quarter:  2001 Q1 <br>Total Trips ('000):  1.6603872","Year & Quarter:  2001 Q2 <br>Total Trips ('000):  9.8777056","Year & Quarter:  2001 Q3 <br>Total Trips ('000):  12.3188681","Year & Quarter:  2001 Q4 <br>Total Trips ('000):  32.5153699","Year & Quarter:  2002 Q1 <br>Total Trips ('000):  4.8082595","Year & Quarter:  2002 Q2 <br>Total Trips ('000):  21.7829561","Year & Quarter:  2002 Q3 <br>Total Trips ('000):  13.5715269","Year & Quarter:  2002 Q4 <br>Total Trips ('000):  20.0850299","Year & Quarter:  2003 Q1 <br>Total Trips ('000):  4.335211","Year & Quarter:  2003 Q2 <br>Total Trips ('000):  11.512479","Year & Quarter:  2003 Q3 <br>Total Trips ('000):  37.7393833","Year & Quarter:  2003 Q4 <br>Total Trips ('000):  7.2644866","Year & Quarter:  2004 Q1 <br>Total Trips ('000):  6.3604437","Year & Quarter:  2004 Q2 <br>Total Trips ('000):  8.7186329","Year & Quarter:  2004 Q3 <br>Total Trips ('000):  19.2818628","Year & Quarter:  2004 Q4 <br>Total Trips ('000):  6.0375512","Year & Quarter:  2005 Q1 <br>Total Trips ('000):  6.5667806","Year & Quarter:  2005 Q2 <br>Total Trips ('000):  9.8268583","Year & Quarter:  2005 Q3 <br>Total Trips ('000):  26.6154127","Year & Quarter:  2005 Q4 <br>Total Trips ('000):  0.7123404","Year & Quarter:  2006 Q1 <br>Total Trips ('000):  9.493673","Year & Quarter:  2006 Q2 <br>Total Trips ('000):  8.145694","Year & Quarter:  2006 Q3 <br>Total Trips ('000):  17.720699","Year & Quarter:  2006 Q4 <br>Total Trips ('000):  6.351099","Year & Quarter:  2007 Q1 <br>Total Trips ('000):  2.6778412","Year & Quarter:  2007 Q2 <br>Total Trips ('000):  5.0403471","Year & Quarter:  2007 Q3 <br>Total Trips ('000):  9.632867","Year & Quarter:  2007 Q4 <br>Total Trips ('000):  10.5855171","Year & Quarter:  2008 Q1 <br>Total Trips ('000):  0.6973548","Year & Quarter:  2008 Q2 <br>Total Trips ('000):  10.9782212","Year & Quarter:  2008 Q3 <br>Total Trips ('000):  19.3209848","Year & Quarter:  2008 Q4 <br>Total Trips ('000):  2.2640463","Year & Quarter:  2009 Q1 <br>Total Trips ('000):  0.7315352","Year & Quarter:  2009 Q2 <br>Total Trips ('000):  11.4648227","Year & Quarter:  2009 Q3 <br>Total Trips ('000):  14.0344182","Year & Quarter:  2009 Q4 <br>Total Trips ('000):  1.1207091","Year & Quarter:  2010 Q1 <br>Total Trips ('000):  5.705516","Year & Quarter:  2010 Q2 <br>Total Trips ('000):  4.9895717","Year & Quarter:  2010 Q3 <br>Total Trips ('000):  19.0904052","Year & Quarter:  2010 Q4 <br>Total Trips ('000):  9.0994248","Year & Quarter:  2011 Q1 <br>Total Trips ('000):  1.9231903","Year & Quarter:  2011 Q2 <br>Total Trips ('000):  3.559571","Year & Quarter:  2011 Q3 <br>Total Trips ('000):  36.5969281","Year & Quarter:  2011 Q4 <br>Total Trips ('000):  5.037328","Year & Quarter:  2012 Q1 <br>Total Trips ('000):  6.7601505","Year & Quarter:  2012 Q2 <br>Total Trips ('000):  7.147062","Year & Quarter:  2012 Q3 <br>Total Trips ('000):  16.0057129","Year & Quarter:  2012 Q4 <br>Total Trips ('000):  7.9012293","Year & Quarter:  2013 Q1 <br>Total Trips ('000):  1.2050858","Year & Quarter:  2013 Q2 <br>Total Trips ('000):  12.1302542","Year & Quarter:  2013 Q3 <br>Total Trips ('000):  13.8955267","Year & Quarter:  2013 Q4 <br>Total Trips ('000):  4.2642349","Year & Quarter:  2014 Q1 <br>Total Trips ('000):  3.7099404","Year & Quarter:  2014 Q2 <br>Total Trips ('000):  5.099115","Year & Quarter:  2014 Q3 <br>Total Trips ('000):  23.6504787","Year & Quarter:  2014 Q4 <br>Total Trips ('000):  10.8560451","Year & Quarter:  2015 Q1 <br>Total Trips ('000):  1.3031109","Year & Quarter:  2015 Q2 <br>Total Trips ('000):  10.9236171","Year & Quarter:  2015 Q3 <br>Total Trips ('000):  17.5995796","Year & Quarter:  2015 Q4 <br>Total Trips ('000):  16.7164817","Year & Quarter:  2016 Q1 <br>Total Trips ('000):  8.6217633","Year & Quarter:  2016 Q2 <br>Total Trips ('000):  14.5267264","Year & Quarter:  2016 Q3 <br>Total Trips ('000):  28.1090854","Year & Quarter:  2016 Q4 <br>Total Trips ('000):  11.2946704","Year & Quarter:  2017 Q1 <br>Total Trips ('000):  8.7897199","Year & Quarter:  2017 Q2 <br>Total Trips ('000):  24.9182584","Year & Quarter:  2017 Q3 <br>Total Trips ('000):  14.7132088","Year & Quarter:  2017 Q4 <br>Total Trips ('000):  9.0363734","Year & Quarter:  2018 Q1 <br>Total Trips ('000):  0","Year & Quarter:  2018 Q2 <br>Total Trips ('000):  23.9037386","Year & Quarter:  2018 Q3 <br>Total Trips ('000):  13.7949632","Year & Quarter:  2018 Q4 <br>Total Trips ('000):  21.4045985","Year & Quarter:  2019 Q1 <br>Total Trips ('000):  6.0704411","Year & Quarter:  2019 Q2 <br>Total Trips ('000):  13.9454448","Year & Quarter:  2019 Q3 <br>Total Trips ('000):  25.4447021","Year & Quarter:  2019 Q4 <br>Total Trips ('000):  10.0180881","Year & Quarter:  2020 Q1 <br>Total Trips ('000):  6.4248418","Year & Quarter:  2020 Q2 <br>Total Trips ('000):  1.525885","Year & Quarter:  2020 Q3 <br>Total Trips ('000):  5.6324325","Year & Quarter:  2020 Q4 <br>Total Trips ('000):  4.3808663","Year & Quarter:  2021 Q1 <br>Total Trips ('000):  1.90053","Year & Quarter:  2021 Q2 <br>Total Trips ('000):  8.6356223","Year & Quarter:  2021 Q3 <br>Total Trips ('000):  14.5708519","Year & Quarter:  2021 Q4 <br>Total Trips ('000):  2.304403","Year & Quarter:  2022 Q1 <br>Total Trips ('000):  0","Year & Quarter:  2022 Q2 <br>Total Trips ('000):  7.7686965","Year & Quarter:  2022 Q3 <br>Total Trips ('000):  18.9704089","Year & Quarter:  2022 Q4 <br>Total Trips ('000):  5.6223744"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(176,48,96,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(176,48,96,1)"}},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":75,"r":7.3059360730593621,"b":40.182648401826491,"l":50},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[9775.0499999999993,19717.950000000001],"tickmode":"array","ticktext":["2000 Q1","2005 Q1","2010 Q1","2015 Q1","2020 Q1"],"tickvals":[10957,12784,14610,16436,18262],"categoryorder":"array","categoryarray":["2000 Q1","2005 Q1","2010 Q1","2015 Q1","2020 Q1"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":true,"linecolor":"rgba(0,0,0,1)","linewidth":0.66417600664176002,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"y","title":{"text":"Year and Quarter","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-1.886969165,39.626352464999997],"tickmode":"array","ticktext":["0","10","20","30"],"tickvals":[0,10,20,30],"categoryorder":"array","categoryarray":["0","10","20","30"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":true,"linecolor":"rgba(0,0,0,1)","linewidth":0.66417600664176002,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"x","title":{"text":"Total Trips ('000)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative","title":{"y":0.92500000000000004,"xref":"plot","text":"Tourist Trips Over Time<br><sup>Region : Barkly<sup>"}},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"29744cec59bf":{"x":{},"y":{},"type":"scatter"},"29745d4b4a89":{"x":{},"y":{},"text":{}}},"cur_data":"29744cec59bf","visdat":{"29744cec59bf":["function (y) ","x"],"29745d4b4a89":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<figcaption class="figure-caption">Figure&nbsp;15: Tourist Trips Over Time (Barkly))</figcaption>
</figure>
</div>
</div>
<p><strong>Discussion</strong></p>
<p>The plot (<a href="#fig-plots13">Figure&nbsp;15</a>) shows the total number of tourist trips over time, grouped by year and quarter. As can be seen, the trend fluctuates significantly from year to year. Notably, Quarter 3 of 2003 saw the Barkly region record its peak number of visits, while in contrast, Quarter 1 of 2022 and Quarter of 2018 have no visitor at all. This broad trend doesn’t provide enough granularity, making it challenging to identify any seasonality that might yield insightful information. Hence, we will delve deeper into this temporal analysis in order to get full understanding on tourism pattern of Barkly region.</p>
</section>
<section id="temporal-trends-by-quarter" class="level4">
<h4 class="anchored" data-anchor-id="temporal-trends-by-quarter">Temporal Trends by Quarter</h4>
<p>Let’s explore the data further by looking at the trend on quarterly basis. By considering quarter spectrum, here we will ignore the year component, we will combine each quarter from all year into one. Through this approach, we are hoping to reveal any pattern arises from the similarity of time.</p>
<p>The location of Barkly Region that is in the middle of the desert may also have a contribution to the number of tourism. Our intuition define a desert area will be very hot during summer, which make it a less suitable place to visit. It will be more suitable in the other season, hence probably one of the factor behind why it is a popular place to visit in Q3 (according to figure (<a href="#fig-plots13">Figure&nbsp;15</a>)). In the graph below, we will try to prove our intuiton by utilising the weather station data that has temperature data.</p>
<div class="cell" data-layout-align="center" data-fig-heigth="6">
<div class="cell-output-display">
<div id="fig-plots15" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots15-1.png" class="img-fluid figure-img" width="1152"></p>
<figcaption class="figure-caption">Figure&nbsp;16: Quarterly Tourism Number (Barkly) &amp; Quarterly Average Temperature (Barkly))</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Discussion</strong></p>
<p>Some interesting insights that are shown in the plot above:</p>
<ul>
<li><p>The left graph in (<a href="#fig-plots15">Figure&nbsp;16</a>) shows the number of tourism for each quarter, it’s evident that Q3 attracts the most tourists, with over 450,000 people visiting Barkly, followed by Q2 with more than 250(’000) people, Q4 with just below 250(’000) people, and last, Q1 with just above than 100(’000) people.</p></li>
<li><p>The right graph in (<a href="#fig-plots15">Figure&nbsp;16</a>) depicts the average temperature trends around Barkly region for each quarter. As can be seen that Q1 and Q4 temperature share a pretty similar range of temperature with around 30 Celsius degree, while Q2 and Q3 hover around a cooler 20 Celsius degree. This is align with the seasonal condition in Australia, where Q1 is the period of summer to fall (higher temperature), Q2 is fall to winter (lower temperature), Q3 is winter to spring (lower temperature), and Q4 is spring to summer (higher temperature).</p></li>
</ul>
<p>Based on above observations, it appears our initial assumption was accurate. Given the desert landscape of Barkly, it’s plausible that the milder temperatures in Q3 make it a more attractive time for tourists. In contrast, Q1 experienced the lowest number of tourism which potentially caused by higher temperature to the area.</p>
</section>
<section id="temporal-trends-by-quarter-for-different-purposes" class="level4">
<h4 class="anchored" data-anchor-id="temporal-trends-by-quarter-for-different-purposes">Temporal Trends by Quarter for Different Purposes</h4>
<p>Now we are going to look at how the tourism activities varies across multiple categories, including holidays, business activities, leisurely visits, and other significant reasons. By looking at this spectrum, we will be able to gain valuable insights into what sort of activities that visiters intended to do in Barkly region, helping us to shape our understanding towards this analysis in general. The graph below will provide us with such information.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots16" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots16-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;17: Temporal Trends by Quarter for Different Purposes (Barkly))</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Discussion</strong></p>
<p>According to the (<a href="#fig-plots16">Figure&nbsp;17</a>) above, it’s evident that all the graphs representing different trip purposes display a fluctuating trend, consistent with the (<a href="#fig-plots15">Figure&nbsp;16</a>). It seems like “Holiday” experienced the most fluctuation, with “Other” is the most steady. From the quantity perspective, “Holiday” come out on top as the main reason, followed by “Business”, “Visiting”, and “Other”. From this graph, we can conclude the Barkly is one of the popular destination when people decide where to spend their holiday to. We are interested to determine if Weeping Mulla Mulla eco-tourism is one of the a contributing factor to this trend.</p>
<p>In the next section, we will utilize all the information we gather around the tourism trend in Barkly region to compare it with Occurrences dataset. Our goal is to determine if there is any specific eco-tourism related to Weeping Mulla Mulla that may have contributed to the significant volume over the number of tourism into Barkly region.</p>
</section>
</section>
<section id="weeping-mulla-mulla-eco-tourism" class="level3">
<h3 class="anchored" data-anchor-id="weeping-mulla-mulla-eco-tourism">Weeping Mulla Mulla Eco-Tourism</h3>
<p>In this part, we will shift our focus into finding the correlation between the sightings of Weeping Mulla Mulla with the number of tourism of Barkly region. We aim to see if the increasing number of tourist visit will also be followed by increasing number of Weeping Mulla Mulla sighting. We will expose any hinder pattern that could not be spotted just by looking at the data separately. Let’s unveil it!</p>
<section id="ecotourist-interest-in-weeping-mulla-mulla" class="level4">
<h4 class="anchored" data-anchor-id="ecotourist-interest-in-weeping-mulla-mulla">Ecotourist interest in Weeping Mulla Mulla</h4>
<p>Before we employ data analysis to reveal any insights regarding this topic, we perform a thorough research on the Weeping Mulla Mulla eco-tourism. Unfortunately, after spending hours looking, there is no single information leading us to any news/articles/announcements related to it, not even local government website. There is no single advertisement by tour &amp; travel organisation that specifically offer an eco-tourism to Barkly region for Weeping Mulla Mulla. As such, our analysis will be based on the data we have on hand, aiming to discern any significant patterns.</p>
<p>We now move on into the data analysis part. Firstly, we narrow down the necessary data related to eco-tourism interest of Weeping Mulla Mulla by filtering out Trips with “Holiday” purpose only. We assume that people who has spotted and reported the occurrences are on their vacation, hence the selection of variable <code>Purpose</code> plays a role here.</p>
<div class="cell" data-layout-align="center">
<div id="fig-plots17" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-093decc56a6f4088e038" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-093decc56a6f4088e038">{"x":{"data":[{"x":[2.0759102999999999],"y":[1],"text":"Year & Quarter: 2005 Q2 <br>Total Visitor ('000):  2.076 <br>Total Sightings:  1","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(248,118,109,1)"}},"hoveron":"points","name":"2005 Q2","legendgroup":"2005 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[17.011084],"y":[1],"text":"Year & Quarter: 2008 Q3 <br>Total Visitor ('000):  17.011 <br>Total Sightings:  1","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(235,131,53,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(235,131,53,1)"}},"hoveron":"points","name":"2008 Q3","legendgroup":"2008 Q3","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0],"y":[1],"text":"Year & Quarter: 2009 Q1 <br>Total Visitor ('000):  0.000 <br>Total Sightings:  1","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(218,143,0,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(218,143,0,1)"}},"hoveron":"points","name":"2009 Q1","legendgroup":"2009 Q1","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2.0103778999999999],"y":[1],"text":"Year & Quarter: 2009 Q2 <br>Total Visitor ('000):  2.010 <br>Total Sightings:  1","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(196,154,0,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(196,154,0,1)"}},"hoveron":"points","name":"2009 Q2","legendgroup":"2009 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[3.6066077000000001],"y":[1],"text":"Year & Quarter: 2010 Q2 <br>Total Visitor ('000):  3.607 <br>Total Sightings:  1","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(169,164,0,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(169,164,0,1)"}},"hoveron":"points","name":"2010 Q2","legendgroup":"2010 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2.6347439000000001],"y":[1],"text":"Year & Quarter: 2012 Q2 <br>Total Visitor ('000):  2.635 <br>Total Sightings:  1","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(134,172,0,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(134,172,0,1)"}},"hoveron":"points","name":"2012 Q2","legendgroup":"2012 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[15.0595602],"y":[1],"text":"Year & Quarter: 2012 Q3 <br>Total Visitor ('000):  15.060 <br>Total Sightings:  1","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(83,180,0,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(83,180,0,1)"}},"hoveron":"points","name":"2012 Q3","legendgroup":"2012 Q3","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[8.3180447999999991],"y":[86],"text":"Year & Quarter: 2015 Q3 <br>Total Visitor ('000):  8.318 <br>Total Sightings:  86","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,186,56,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,186,56,1)"}},"hoveron":"points","name":"2015 Q3","legendgroup":"2015 Q3","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[16.570807599999998],"y":[19],"text":"Year & Quarter: 2015 Q4 <br>Total Visitor ('000):  16.571 <br>Total Sightings:  19","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,190,109,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,190,109,1)"}},"hoveron":"points","name":"2015 Q4","legendgroup":"2015 Q4","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[2.4453592999999998],"y":[2],"text":"Year & Quarter: 2016 Q1 <br>Total Visitor ('000):  2.445 <br>Total Sightings:  2","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,192,148,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,192,148,1)"}},"hoveron":"points","name":"2016 Q1","legendgroup":"2016 Q1","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[13.5923464],"y":[29],"text":"Year & Quarter: 2016 Q2 <br>Total Visitor ('000):  13.592 <br>Total Sightings:  29","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,192,181,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,192,181,1)"}},"hoveron":"points","name":"2016 Q2","legendgroup":"2016 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[14.120391],"y":[1],"text":"Year & Quarter: 2017 Q2 <br>Total Visitor ('000):  14.120 <br>Total Sightings:  1","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,189,210,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,189,210,1)"}},"hoveron":"points","name":"2017 Q2","legendgroup":"2017 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[1.8568169999999999],"y":[2],"text":"Year & Quarter: 2019 Q1 <br>Total Visitor ('000):  1.857 <br>Total Sightings:  2","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,182,235,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,182,235,1)"}},"hoveron":"points","name":"2019 Q1","legendgroup":"2019 Q1","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0],"y":[2],"text":"Year & Quarter: 2019 Q2 <br>Total Visitor ('000):  0.000 <br>Total Sightings:  2","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(0,171,253,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(0,171,253,1)"}},"hoveron":"points","name":"2019 Q2","legendgroup":"2019 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[21.722032200000001],"y":[2],"text":"Year & Quarter: 2019 Q3 <br>Total Visitor ('000):  21.722 <br>Total Sightings:  2","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(97,156,255,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(97,156,255,1)"}},"hoveron":"points","name":"2019 Q3","legendgroup":"2019 Q3","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[1.9005300000000001],"y":[3],"text":"Year & Quarter: 2021 Q1 <br>Total Visitor ('000):  1.901 <br>Total Sightings:  3","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(165,138,255,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(165,138,255,1)"}},"hoveron":"points","name":"2021 Q1","legendgroup":"2021 Q1","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[8.6356222999999996],"y":[3],"text":"Year & Quarter: 2021 Q2 <br>Total Visitor ('000):  8.636 <br>Total Sightings:  3","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(208,120,255,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(208,120,255,1)"}},"hoveron":"points","name":"2021 Q2","legendgroup":"2021 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[14.570851899999999],"y":[2],"text":"Year & Quarter: 2021 Q3 <br>Total Visitor ('000):  14.571 <br>Total Sightings:  2","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(236,105,239,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(236,105,239,1)"}},"hoveron":"points","name":"2021 Q3","legendgroup":"2021 Q3","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[0],"y":[2],"text":"Year & Quarter: 2022 Q1 <br>Total Visitor ('000):  0.000 <br>Total Sightings:  2","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(251,97,215,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(251,97,215,1)"}},"hoveron":"points","name":"2022 Q1","legendgroup":"2022 Q1","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[6.2756778000000004],"y":[3],"text":"Year & Quarter: 2022 Q2 <br>Total Visitor ('000):  6.276 <br>Total Sightings:  3","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(255,99,185,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(255,99,185,1)"}},"hoveron":"points","name":"2022 Q2","legendgroup":"2022 Q2","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[18.970408899999999],"y":[2],"text":"Year & Quarter: 2022 Q3 <br>Total Visitor ('000):  18.970 <br>Total Sightings:  2","type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(255,107,150,1)","opacity":1,"size":7.559055118110237,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(255,107,150,1)"}},"hoveron":"points","name":"2022 Q3","legendgroup":"2022 Q3","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":75,"r":7.3059360730593621,"b":40.182648401826491,"l":50},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-1.0861016100000001,22.808133810000001],"tickmode":"array","ticktext":["0","5","10","15","20"],"tickvals":[0,5,10,15,20],"categoryorder":"array","categoryarray":["0","5","10","15","20"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":true,"linecolor":"rgba(0,0,0,1)","linewidth":0.66417600664176002,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"y","title":{"text":"Number of Visiting Tourist ('000)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-3.25,90.25],"tickmode":"array","ticktext":["0","25","50","75"],"tickvals":[0,25,49.999999999999993,75],"categoryorder":"array","categoryarray":["0","25","50","75"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":true,"linecolor":"rgba(0,0,0,1)","linewidth":0.66417600664176002,"showgrid":false,"gridcolor":null,"gridwidth":0,"zeroline":false,"anchor":"x","title":{"text":"Number of Sightings","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative","title":{"y":0.92500000000000004,"xref":"plot","text":"Correlation between Number of Tourist to Weeping Mulla Mulla Sightings<br><sup>Region : Barkly<sup>"}},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"29746688aa7":{"x":{},"y":{},"colour":{},"text":{},"type":"scatter"}},"cur_data":"29746688aa7","visdat":{"29746688aa7":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<figcaption class="figure-caption">Figure&nbsp;18: Correlation between Number of Tourist to Weeping Mulla Mulla Sightings (Barkly))</figcaption>
</figure>
</div>
</div>
<p><strong>Discussion</strong></p>
<p>Through a visual representation of number of tourist to number of sightings from the (<a href="#fig-plots17">Figure&nbsp;18</a>), we can clearly see there is no correlation between them. The increasing number of visitor to Barkly is not followed by the increasing number of Weeping Mulla Mulla sightings. For instance, Quarter 3 of 2015, which recorded the top number of sightings, isn’t even within the top five quarters for tourist visits. In contrast, Quarter 3 of 2019, which had the highest number of tourist visits, recorded only two sightings. This indicates that Weeping Mulla Mulla observation potentially is not one of the deciding factor people go to Barkly.</p>
</section>
<section id="visual-inference-of-tourism-sightings" class="level4">
<h4 class="anchored" data-anchor-id="visual-inference-of-tourism-sightings">Visual Inference of Tourism &amp; Sightings</h4>
<p>In supporting our discussion, we made a visual inference and asked some of our friends if they can distinguish the null plot that produced by permutating the variable.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots18" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots18-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;19: Visual Inference</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p><span class="math inline">\(H_0:\)</span>: There is no relationship between number of tourist visiting a certain region to the number of sightings of Weeping Mulla Mulla in that same region.</p></li>
<li><p><span class="math inline">\(H_1:\)</span>: There is strong relationship between number of tourist visiting a certain region to the number of sightings of Weeping Mulla Mulla in that same region.</p></li>
</ul>
<p>The result for p-value</p>
<p>x = 1 people</p>
<p>n = 10 people</p>
<p>p-value computation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>nullabor<span class="sc">::</span><span class="fu">pvisual</span>(<span class="dv">1</span>,<span class="dv">10</span>,<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     x simulated     binom
[1,] 1    0.3707 0.4012631</code></pre>
</div>
</div>
<p>From the computation, <code>x simulated</code> shows 0.3707 and <code>binom</code> shows 0.4012631, meaning the p-value of correlation plot is 0.401 or 40.1%. Since it is more than 0.05 or 5% (significance level), then we will accept H0. This mean there is weak linear relationship between number of tourism and number of sightings. The majority of the participants in the survey expressed that identifying the most distinct plot from the selection is quite challenging due to the similarity in patterns among all of them.</p>
</section>
<section id="spatial-analysis-of-tourism-and-occurences" class="level4">
<h4 class="anchored" data-anchor-id="spatial-analysis-of-tourism-and-occurences">Spatial Analysis of Tourism and Occurences</h4>
<p>Our current data doesn’t provide enough support to solidify the connection between Weeping Mulla Mulla and tourism number, and it remains inconclusive whether the influx of visitors to Barkly was partially driven by the prominence of the Weeping Mulla Mulla. A more detailed perspective can be gained by examining the subsequent map, which will place Weeping Mulla Mulla’s sightings with the number of trips to multiple regions.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-plots19" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="report_files/figure-html/fig-plots19-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;20: Mapping correlation between the Number of Tourist and Weeping Mulla Mulla Sightings</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">

<div id="htmlwidget-a52498cf4af0e114dde4" style="width:100%;height:40%;" class="datatables html-widget "></div>
<script type="application/json" data-for="htmlwidget-a52498cf4af0e114dde4">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83"],["Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Northern Territory","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia","Western Australia"],["Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Barkly","Elsey","Elsey","Gulf","Tanami","Tanami","Tanami","Victoria River","Victoria River","Victoria River","Victoria River","Victoria River","Victoria River","Victoria River","Victoria River","Yuendumu - Anmatjere","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Ashburton (WA)","Derby - West Kimberley","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","East Pilbara","Halls Creek","Halls Creek","Halls Creek","Halls Creek","Halls Creek","Halls Creek","Halls Creek","Halls Creek","Kununurra","Kununurra","Leinster - Leonora","Roebourne","Roebourne","Roebuck","Roebuck","Roebuck","Roebuck"],[2005,2008,2009,2009,2010,2012,2012,2015,2015,2016,2016,2017,2019,2019,2019,2021,2021,2021,2022,2022,2022,2009,2020,2020,2004,2019,2021,1998,2001,2004,2007,2010,2012,2012,2021,2021,2004,2009,2015,2017,2018,2018,2019,2020,2021,2021,2022,2022,2022,2021,2006,2015,2017,2019,2020,2020,2020,2021,2021,2021,2021,2022,2019,2021,2022,2022,2008,2017,2018,2019,2021,2022,2022,2022,2008,2021,2013,2020,2021,2021,2021,2022,2022],["Q2","Q3","Q1","Q2","Q2","Q2","Q3","Q3","Q4","Q1","Q2","Q2","Q1","Q2","Q3","Q1","Q2","Q3","Q1","Q2","Q3","Q3","Q2","Q2","Q2","Q3","Q2","Q2","Q2","Q2","Q3","Q3","Q1","Q2","Q3","Q3","Q3","Q3","Q3","Q3","Q2","Q4","Q3","Q3","Q2","Q3","Q2","Q3","Q4","Q3","Q2","Q3","Q3","Q3","Q2","Q3","Q4","Q1","Q2","Q3","Q4","Q3","Q3","Q3","Q3","Q4","Q3","Q3","Q2","Q2","Q3","Q1","Q2","Q3","Q2","Q3","Q3","Q3","Q2","Q1","Q3","Q3","Q4"],[2.0759103,17.011084,0,2.0103779,3.6066077,2.6347439,15.0595602,8.318044799999999,16.5708076,2.4453593,13.5923464,14.120391,1.856817,0,21.7220322,1.90053,8.6356223,14.5708519,0,6.2756778,18.9704089,15.3089921,4.8563368,0,0.8739217,14.5266885,12.0165083,0,16.1086266,4.3636259,4.7912308,0.9887793,1.3289381,1.0207766,9.0029319,2.3179076,39.2801869,10.6943969,7.5060989,41.2128113,21.8048135,11.7692496,21.1455424,40.9369285,7.0297614,48.5088834,7.1013592,24.1898856,7.7455005,30.1887021,2.543424,10.8643198,15.196041,13.2463446,0,2.8275691,7.7658537,0,5.2454787,23.4980148,1.5485256,3.7660826,13.2463446,23.4980148,3.7660826,2.5699059,13.8478124,31.394005,2.1507934,4.2328296,20.0062379,0,21.3172008,22.0262262,9.994331900000001,43.7249648,6.6686774,10.4504143,10.5521959,0,21.2441266,18.2617957,3.6516771],["Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday","Holiday"],[1,1,1,1,1,1,1,86,19,2,29,1,2,2,2,3,3,2,2,3,2,1,1,1,10,1,1,1,1,2,2,2,2,2,4,1,1,1,2,6,1,1,2,1,2,3,1,2,1,1,1,1,1,1,1,2,2,1,3,1,1,2,1,1,1,1,1,3,1,1,1,1,1,1,1,1,2,1,2,1,2,1,1]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>state<\/th>\n      <th>region<\/th>\n      <th>Year<\/th>\n      <th>Quarter<\/th>\n      <th>Trips<\/th>\n      <th>Purpose<\/th>\n      <th>Total_Sightings<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"scrollX":true,"columnDefs":[{"className":"dt-right","targets":[3,5,7]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false,"rowCallback":"function(row, data, displayNum, displayIndex, dataIndex) {\nvar value=data[1]; $(this.api().cell(row, 1).node()).css({'font-size':'80%'});\nvar value=data[2]; $(this.api().cell(row, 2).node()).css({'font-size':'80%'});\nvar value=data[3]; $(this.api().cell(row, 3).node()).css({'font-size':'80%'});\nvar value=data[4]; $(this.api().cell(row, 4).node()).css({'font-size':'80%'});\nvar value=data[5]; $(this.api().cell(row, 5).node()).css({'font-size':'80%'});\nvar value=data[6]; $(this.api().cell(row, 6).node()).css({'font-size':'80%'});\nvar value=data[7]; $(this.api().cell(row, 7).node()).css({'font-size':'80%'});\n}"}},"evals":["options.rowCallback"],"jsHooks":[]}</script>
</div>
</div>
<p><strong>Discussion</strong></p>
<p>Building on our prior discussion, the map in (<a href="#fig-plots18">Figure&nbsp;19</a>) offers an insightful visualisation of the relationship between Weeping Mulla Mulla occurrences and tourism numbers. A bit different approach to previous analysis, in here, we are including all regions that recording occurrence numbers. We did this because we want to see if the data tells opposite fact when we consider other regions. By utilising spatial analysis, it will provide holistic view and expedite the understanding process. On the map visual itself, the left side is a map of all regions where sightings are recorded, while on the right side is just Barkly region only (our primary region).</p>
<p>The map illustrates a prominent presence of Weeping Mulla Mulla in the North-central areas of Western Australia and parts of the Northern Territory. Notably, the regions with more number of tourist are presented with lighter color, and the darker color represent fewer number of tourist. As can be seen, the regions with higher number of tourism are not the regions where the most sightings recorded. The number could just be contributed from other essential factors, such as popular attractions, infrastructural development, or easier accessibility. So, this spatial analysis supports our previous analysis which could not see any correlation between these two events. Ultimately, this also align with our research about Weeping Mulla Mulla eco-tourism which gave us no information.</p>
</section>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Our analysis of the Weeping Mulla Mulla has confirmed or debunked several key expectations:</p>
<ol type="1">
<li><p><strong>Spatial Distribution</strong>: The species’ sightings are concentrated in the north of Western Australia and in the Northern Territory, forming the two primary clusters of observations.</p></li>
<li><p><strong>Temporal Patterns</strong>: The majority of Weeping Mulla Mulla sightings occur between March and October, in line with its thriving period during these months.</p></li>
<li><p><strong>Trend Confirmation</strong>: We have observed a consistent number of sightings with an increasing trend, attributed to enhanced sighting, reporting, and monitoring methods, particularly evident since 2015. Remarkably, there was no decline in observations even during the COVID lockdown period.</p></li>
<li><p><strong>Habitat Preferences</strong>: Initial expectations were that sightings would cluster around areas with a water source, given the plant’s preference for harsh, dry, and hot sandy habitats. However, our analysis reveals a surprising finding. The primary cluster of sightings does not necessarily align with water sources, indicating the plant’s reliance on rain for survival. Additionally, sightings are frequently reported near roads, suggesting observations by passersby.</p></li>
<li><p><strong>Rainfall Influence</strong>: Considering that the Weeping Mulla Mulla typically blooms after the wet season, which occurs approximately between June and August, we conducted an in-depth analysis of rainfall and precipitation. Intriguingly, while there were more sightings in March and April during the blooming cycle and occasional showers, there was a decrease in sightings during thunderstorms and flooding in June and July. The highest number of sightings was recorded in August, likely attributed to milder downpours. This observation aligns with the inherent nature of the Weeping Mulla Mulla as a desert plant that thrives without relying heavily on water.</p></li>
<li><p><strong>Tourism Peak Seasons</strong>: Examining the Barkly region’s tourism patterns in detail, particularly in the area surrounding Tennant Creek Airport, reveals that visitors vary over time. Quarter 3 of 2003 has a noteworthy high, whereas some quarters—like Q1 2022—recorded zero tourists. Additional information gleaned from the quarterly analysis suggests possible seasonal trends. Considering Barkly’s desert terrain and the temperature data from nearby weather stations, it seems that Q3’s cooler temperatures provide a more enticing window of time for visitors. In addition, our research indicates that the Barkly region is a popular destination for vacationers.</p></li>
<li><p><strong>Eco-tourism Insights</strong>: Examining the potential association between sightings of Weeping Mulla Mulla and eco-tourism, the study is unable to find proof of a direct connection. According to the data research, even areas where there are a lot of tourist visit did not resulted in higher number of sightings. An in-depth geographical examination, comparing the number of Weeping Mulla Mulla sightings with the number of tourists in various locations, validates this finding. It suggests that factors other than Weeping Mulla Mulla sightings might affect visitor patterns.</p></li>
</ol>
<p>In conclusion, the findings in this report affirm that the <strong>Weeping Mulla Mulla</strong> is an exceptionally unique and endemic plant, exclusively located in the northern regions of Australia. Tourists seeking to experience the harsh desert climate can observe it at its peak during the months of March to October. This desert plant thrives with minimal water requirements for survival. In addition, while the Barkly region attracts tourists for various reasons, the presence of the Weeping Mulla Mulla doesn’t significantly influence tourist numbers. Despite its uniqueness, the eco-tourism potential of this plant remains relatively unexplored.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<section id="websites" class="level3">
<h3 class="anchored" data-anchor-id="websites">Websites</h3>
<ul>
<li><strong>iNaturalist</strong>. Ptilotus calostachyus Image., Retrieved October 03, 2023, from https://www.inaturalist.org/taxa/869581-Ptilotus-calostachyus.</li>
<li><strong>Florabase</strong>, Ptilotus calostachyus F.Muell., Retrieved September 29, 2023, from https://florabase.dbca.wa.gov.au/browse/profile.php/2704</li>
<li><strong>The Atlas of Living Australia</strong>. Ptilotus calostachyus F.Muell. Retrieved September 27, 2023, from https://bie.ala.org.au/species/https://id.biodiversity.org.au/node/apni/2910906# overview</li>
<li><strong>Tourism NT</strong>. Annual Report 2015-16. Retrieved October 26, 2023, from https://parliament.nt.gov.au/__data/assets/pdf_file/0005/385952/185.-Annual-Report-2015-2016,-Tourism-NT.pdf</li>
</ul>
</section>
<section id="packages" class="level3">
<h3 class="anchored" data-anchor-id="packages">Packages</h3>
<ul>
<li><strong>cowplot</strong>: Wilke C (2020). <em>cowplot: Streamlined Plot Theme and Plot Annotations for ‘ggplot2’</em>. R package version 1.1.1, https://CRAN.R-project.org/package=cowplot.</li>
<li><strong>galah</strong>: Westgate M, Kellie D, Stevenson M, Newman P (2023). <em>galah: Biodiversity Data from the Living Atlas Community</em>. R package version 1.5.3, https://CRAN.R-project.org/package=galah.</li>
<li><strong>kableExtra</strong>: Zhu H (2021). <em>kableExtra: Construct Complex Table with ‘kable’ and Pipe Syntax</em>. R package version 1.3.4, https://CRAN.R-project.org/package=kableExtra.</li>
<li><strong>leaflet</strong>: Cheng J, Schloerke B, Karambelkar B, Xie Y (2023). <em>leaflet: Create Interactive Web Maps with the JavaScript ‘Leaflet’ Library</em>. R package version 2.2.0, https://CRAN.R-project.org/package=leaflet.</li>
<li><strong>nullabor</strong>: Buja, A., Cook, D., Hofmann, H., Lawrence, M., Lee, E.-K., Swayne, D. F, Wickham, H. (2009) Statistical Inference for Exploratory Data Analysis and Model Diagnostics Royal Society Philosophical Transactions A, 367(1906):4361-4383. URL http://rsta.royalsocietypublishing.org/content/367/1906/4361.article-info</li>
<li><strong>plotly</strong>: C. Sievert. Interactive Web-Based Data Visualization with R, plotly, and shiny. Chapman and Hall/CRC Florida, 2020.</li>
<li><strong>rnoaa</strong>: Chamberlain S, Hocking D (2023). <em>rnoaa: ‘NOAA’ Weather Data from R</em>. R package version 1.4.0, https://CRAN.R-project.org/package=rnoaa.</li>
<li><strong>spData</strong>: Bivand R, Nowosad J, Lovelace R (2023). <em>spData: Datasets for Spatial Analysis</em>. R</li>
<li><strong>tidyverse</strong>: Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). “Welcome to the tidyverse.” <em>Journal of Open Source Software</em>, <em>4</em>(43), 1686. doi:10.21105/joss.01686 https://doi.org/10.21105/joss.01686.</li>
<li><strong>visdat</strong>: Tierney N (2017). “visdat: Visualising Whole Data Frames.” <em>JOSS</em>, <em>2</em>(16), 355. doi:10.21105/joss.00355 https://doi.org/10.21105/joss.00355, http://dx.doi.org/10.21105/joss.00355.</li>
<li><strong>tsibble</strong>: Wang, E, D Cook, and RJ Hyndman (2020). A new tidy data structure to support exploration and modeling of temporal data, Journal of Computational and Graphical Statistics, 29:3, 466-478, doi:10.1080/10618600.2019.1695624.<br>
</li>
<li><strong>lubridate</strong>: Garrett Grolemund, Hadley Wickham (2011). Dates and Times Made Easy with lubridate. Journal of Statistical Software, 40(3), 1-25. URL https://www.jstatsoft.org/v40/i03/.<br>
</li>
<li><strong>sf</strong>: Pebesma, E., &amp; Bivand, R. (2023). Spatial Data Science: With Applications in R. Chapman and Hall/CRC. https://doi.org/10.1201/9780429459016</li>
<li><strong>rmapshaper</strong>: Teucher A, Russell K (2023). <em>rmapshaper: Client for ‘mapshaper’ for ‘Geospatial’ Operations</em>. R package version 0.5.0, <a href="https://CRAN.R-project.org/package=rmapshaper" class="uri">https://CRAN.R-project.org/package=rmapshaper</a>.</li>
<li><strong>zoo</strong>: Zeileis A, Grothendieck G (2005). “zoo: S3 Infrastructure for Regular and Irregular Time Series.” <em>Journal of Statistical Software</em>, <em>14</em>(6), 1-27. doi:10.18637/jss.v014.i06 <a href="https://doi.org/10.18637/jss.v014.i06" class="uri">https://doi.org/10.18637/jss.v014.i06</a>.</li>
<li><strong>cubble</strong>: Zhang H, Cook D, Laa U, Langrené N, Menéndez P (2023). <em>cubble: A Vector Spatio-Temporal Data Structure for Data Analysis</em>. R package version 0.3.0, <a href="https://github.com/huizezhang-sherry/cubble" class="uri">https://github.com/huizezhang-sherry/cubble</a>.</li>
<li><strong>gridExtra</strong>: Auguie B (2017). <em>gridExtra: Miscellaneous Functions for “Grid” Graphics</em>. R package version 2.3, <a href="https://CRAN.R-project.org/package=gridExtra" class="uri">https://CRAN.R-project.org/package=gridExtra</a>.</li>
<li><strong>DT</strong>: Xie Y, Cheng J, Tan X (2023). <em>DT: A Wrapper of the JavaScript Library ‘DataTables’</em>. R package version 0.28, <a href="https://CRAN.R-project.org/package=DT" class="uri">https://CRAN.R-project.org/package=DT</a>.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>